PROC REFILL_OWNED_WEAPON(PED_INDEX ped, WEAPON_TYPE weapon)
    INT maxAmmo = 0
    IF HAS_PED_GOT_WEAPON(ped, weapon)
        IF GET_MAX_AMMO(ped, weapon, maxAmmo)
            SET_PED_AMMO(ped, weapon, maxAmmo)
        ENDIF
    ENDIF
ENDPROC

PROC REFILL_ALL_OWNED_WEAPONS(PED_INDEX ped)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_PISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_COMBATPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_APPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_MICROSMG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_SMG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_ASSAULTRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_CARBINERIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_ADVANCEDRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_MG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_COMBATMG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_PUMPSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_SAWNOFFSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_ASSAULTSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_SNIPERRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_HEAVYSNIPER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_GRENADELAUNCHER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_GRENADELAUNCHER_SMOKE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_RPG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_MINIGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_GRENADE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_SMOKEGRENADE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_BZGAS)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_STICKYBOMB)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_MOLOTOV)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_FLARE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_STUNGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_FIREEXTINGUISHER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_PETROLCAN)

    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_PISTOL50)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_SNSPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_HEAVYPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_VINTAGEPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MARKSMANPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_REVOLVER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_SNSPISTOL_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_REVOLVER_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_ASSAULTSMG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_COMBATPDW)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MACHINEPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MINISMG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_GUSENBERG)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_SPECIALCARBINE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_BULLPUPRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_COMPACTRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_ASSAULTRIFLE_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_CARBINERIFLE_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_SPECIALCARBINE_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_COMBATMG_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_BULLPUPSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_HEAVYSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_DBSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_AUTOSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_PUMPSHOTGUN_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MARKSMANRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_HEAVYSNIPER_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MARKSMANRIFLE_MK2)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_HOMINGLAUNCHER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_COMPACTLAUNCHER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_RAILGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_FIREWORK)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MUSKET)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_PROXMINE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_PIPEBOMB)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_SNOWBALL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_FLAREGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_BOTTLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_DAGGER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_KNUCKLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MACHETE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_SWITCHBLADE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_BATTLEAXE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_HATCHET)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_POOLCUE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_WRENCH)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_RAYPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_RAYCARBINE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_RAYMINIGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_DOUBLEACTION)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_STONE_HATCHET)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_CERAMICPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_HAZARDCAN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_NAVYREVOLVER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_GADGETPISTOL)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_MILITARYRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_COMBATSHOTGUN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_HEAVYRIFLE)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_EMPLAUNCHER)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_FERTILIZERCAN)
    REFILL_OWNED_WEAPON(ped, WEAPONTYPE_DLC_STUNGUNG_MP)
ENDPROC

PROC GIVE_ALL_MENU_WEAPONS(PED_INDEX ped)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_PISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_COMBATPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_APPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_PISTOL50, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_SNSPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_HEAVYPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_VINTAGEPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MARKSMANPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_REVOLVER, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_SNSPISTOL_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_REVOLVER_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_MICROSMG, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_SMG, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_ASSAULTSMG, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_COMBATPDW, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MACHINEPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MINISMG, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_GUSENBERG, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_ASSAULTRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_CARBINERIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_ADVANCEDRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_SPECIALCARBINE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_BULLPUPRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_COMPACTRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_ASSAULTRIFLE_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_CARBINERIFLE_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_SPECIALCARBINE_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_MG, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_COMBATMG, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_COMBATMG_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_PUMPSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_SAWNOFFSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_ASSAULTSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_BULLPUPSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_HEAVYSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_DBSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_AUTOSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_PUMPSHOTGUN_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_SNIPERRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_HEAVYSNIPER, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MARKSMANRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_HEAVYSNIPER_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MARKSMANRIFLE_MK2, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_GRENADELAUNCHER, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_RPG, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_MINIGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_HOMINGLAUNCHER, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_COMPACTLAUNCHER, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_RAILGUN, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_FIREWORK, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MUSKET, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_GRENADE, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_SMOKEGRENADE, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_BZGAS, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_STICKYBOMB, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_MOLOTOV, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_PROXMINE, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_PIPEBOMB, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_SNOWBALL, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_FLAREGUN, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_STUNGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_FIREEXTINGUISHER, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_PETROLCAN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_KNIFE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_NIGHTSTICK, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_HAMMER, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_BAT, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_CROWBAR, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_GOLFCLUB, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_BOTTLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_DAGGER, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_KNUCKLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MACHETE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_SWITCHBLADE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_BATTLEAXE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_HATCHET, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_POOLCUE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_WRENCH, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_RAYPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_RAYCARBINE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_RAYMINIGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_DOUBLEACTION, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_STONE_HATCHET, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_CERAMICPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_HAZARDCAN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_NAVYREVOLVER, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_GADGETPISTOL, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_MILITARYRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_COMBATSHOTGUN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_HEAVYRIFLE, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_EMPLAUNCHER, 25, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_FERTILIZERCAN, 9999, TRUE)
    GIVE_DELAYED_WEAPON_TO_PED(ped, WEAPONTYPE_DLC_STUNGUNG_MP, 9999, TRUE)
ENDPROC


FUNC INT MENU_WEAPON_COUNT()
    RETURN 93
ENDFUNC

FUNC WEAPON_TYPE MENU_WEAPON_FOR_CHOICE(INT choice)
    SWITCH choice
        CASE 0 RETURN WEAPONTYPE_PISTOL BREAK
        CASE 1 RETURN WEAPONTYPE_COMBATPISTOL BREAK
        CASE 2 RETURN WEAPONTYPE_APPISTOL BREAK
        CASE 3 RETURN WEAPONTYPE_DLC_PISTOL50 BREAK
        CASE 4 RETURN WEAPONTYPE_DLC_SNSPISTOL BREAK
        CASE 5 RETURN WEAPONTYPE_DLC_HEAVYPISTOL BREAK
        CASE 6 RETURN WEAPONTYPE_DLC_VINTAGEPISTOL BREAK
        CASE 7 RETURN WEAPONTYPE_DLC_MARKSMANPISTOL BREAK
        CASE 8 RETURN WEAPONTYPE_DLC_REVOLVER BREAK
        CASE 9 RETURN WEAPONTYPE_DLC_SNSPISTOL_MK2 BREAK
        CASE 10 RETURN WEAPONTYPE_DLC_REVOLVER_MK2 BREAK
        CASE 11 RETURN WEAPONTYPE_MICROSMG BREAK
        CASE 12 RETURN WEAPONTYPE_SMG BREAK
        CASE 13 RETURN WEAPONTYPE_DLC_ASSAULTSMG BREAK
        CASE 14 RETURN WEAPONTYPE_DLC_COMBATPDW BREAK
        CASE 15 RETURN WEAPONTYPE_DLC_MACHINEPISTOL BREAK
        CASE 16 RETURN WEAPONTYPE_DLC_MINISMG BREAK
        CASE 17 RETURN WEAPONTYPE_DLC_GUSENBERG BREAK
        CASE 18 RETURN WEAPONTYPE_ASSAULTRIFLE BREAK
        CASE 19 RETURN WEAPONTYPE_CARBINERIFLE BREAK
        CASE 20 RETURN WEAPONTYPE_ADVANCEDRIFLE BREAK
        CASE 21 RETURN WEAPONTYPE_DLC_SPECIALCARBINE BREAK
        CASE 22 RETURN WEAPONTYPE_DLC_BULLPUPRIFLE BREAK
        CASE 23 RETURN WEAPONTYPE_DLC_COMPACTRIFLE BREAK
        CASE 24 RETURN WEAPONTYPE_DLC_ASSAULTRIFLE_MK2 BREAK
        CASE 25 RETURN WEAPONTYPE_DLC_CARBINERIFLE_MK2 BREAK
        CASE 26 RETURN WEAPONTYPE_DLC_SPECIALCARBINE_MK2 BREAK
        CASE 27 RETURN WEAPONTYPE_MG BREAK
        CASE 28 RETURN WEAPONTYPE_COMBATMG BREAK
        CASE 29 RETURN WEAPONTYPE_DLC_COMBATMG_MK2 BREAK
        CASE 30 RETURN WEAPONTYPE_PUMPSHOTGUN BREAK
        CASE 31 RETURN WEAPONTYPE_SAWNOFFSHOTGUN BREAK
        CASE 32 RETURN WEAPONTYPE_ASSAULTSHOTGUN BREAK
        CASE 33 RETURN WEAPONTYPE_DLC_BULLPUPSHOTGUN BREAK
        CASE 34 RETURN WEAPONTYPE_DLC_HEAVYSHOTGUN BREAK
        CASE 35 RETURN WEAPONTYPE_DLC_DBSHOTGUN BREAK
        CASE 36 RETURN WEAPONTYPE_DLC_AUTOSHOTGUN BREAK
        CASE 37 RETURN WEAPONTYPE_DLC_PUMPSHOTGUN_MK2 BREAK
        CASE 38 RETURN WEAPONTYPE_SNIPERRIFLE BREAK
        CASE 39 RETURN WEAPONTYPE_HEAVYSNIPER BREAK
        CASE 40 RETURN WEAPONTYPE_DLC_MARKSMANRIFLE BREAK
        CASE 41 RETURN WEAPONTYPE_DLC_HEAVYSNIPER_MK2 BREAK
        CASE 42 RETURN WEAPONTYPE_DLC_MARKSMANRIFLE_MK2 BREAK
        CASE 43 RETURN WEAPONTYPE_GRENADELAUNCHER BREAK
        CASE 44 RETURN WEAPONTYPE_RPG BREAK
        CASE 45 RETURN WEAPONTYPE_MINIGUN BREAK
        CASE 46 RETURN WEAPONTYPE_DLC_HOMINGLAUNCHER BREAK
        CASE 47 RETURN WEAPONTYPE_DLC_COMPACTLAUNCHER BREAK
        CASE 48 RETURN WEAPONTYPE_DLC_RAILGUN BREAK
        CASE 49 RETURN WEAPONTYPE_DLC_FIREWORK BREAK
        CASE 50 RETURN WEAPONTYPE_DLC_MUSKET BREAK
        CASE 51 RETURN WEAPONTYPE_GRENADE BREAK
        CASE 52 RETURN WEAPONTYPE_SMOKEGRENADE BREAK
        CASE 53 RETURN WEAPONTYPE_BZGAS BREAK
        CASE 54 RETURN WEAPONTYPE_STICKYBOMB BREAK
        CASE 55 RETURN WEAPONTYPE_MOLOTOV BREAK
        CASE 56 RETURN WEAPONTYPE_DLC_PROXMINE BREAK
        CASE 57 RETURN WEAPONTYPE_DLC_PIPEBOMB BREAK
        CASE 58 RETURN WEAPONTYPE_DLC_SNOWBALL BREAK
        CASE 59 RETURN WEAPONTYPE_DLC_FLAREGUN BREAK
        CASE 60 RETURN WEAPONTYPE_STUNGUN BREAK
        CASE 61 RETURN WEAPONTYPE_FIREEXTINGUISHER BREAK
        CASE 62 RETURN WEAPONTYPE_PETROLCAN BREAK
        CASE 63 RETURN WEAPONTYPE_KNIFE BREAK
        CASE 64 RETURN WEAPONTYPE_NIGHTSTICK BREAK
        CASE 65 RETURN WEAPONTYPE_HAMMER BREAK
        CASE 66 RETURN WEAPONTYPE_BAT BREAK
        CASE 67 RETURN WEAPONTYPE_CROWBAR BREAK
        CASE 68 RETURN WEAPONTYPE_GOLFCLUB BREAK
        CASE 69 RETURN WEAPONTYPE_DLC_BOTTLE BREAK
        CASE 70 RETURN WEAPONTYPE_DLC_DAGGER BREAK
        CASE 71 RETURN WEAPONTYPE_DLC_KNUCKLE BREAK
        CASE 72 RETURN WEAPONTYPE_DLC_MACHETE BREAK
        CASE 73 RETURN WEAPONTYPE_DLC_SWITCHBLADE BREAK
        CASE 74 RETURN WEAPONTYPE_DLC_BATTLEAXE BREAK
        CASE 75 RETURN WEAPONTYPE_DLC_HATCHET BREAK
        CASE 76 RETURN WEAPONTYPE_DLC_POOLCUE BREAK
        CASE 77 RETURN WEAPONTYPE_DLC_WRENCH BREAK
        CASE 78 RETURN WEAPONTYPE_DLC_RAYPISTOL BREAK
        CASE 79 RETURN WEAPONTYPE_DLC_RAYCARBINE BREAK
        CASE 80 RETURN WEAPONTYPE_DLC_RAYMINIGUN BREAK
        CASE 81 RETURN WEAPONTYPE_DLC_DOUBLEACTION BREAK
        CASE 82 RETURN WEAPONTYPE_DLC_STONE_HATCHET BREAK
        CASE 83 RETURN WEAPONTYPE_DLC_CERAMICPISTOL BREAK
        CASE 84 RETURN WEAPONTYPE_DLC_HAZARDCAN BREAK
        CASE 85 RETURN WEAPONTYPE_DLC_NAVYREVOLVER BREAK
        CASE 86 RETURN WEAPONTYPE_DLC_GADGETPISTOL BREAK
        CASE 87 RETURN WEAPONTYPE_DLC_MILITARYRIFLE BREAK
        CASE 88 RETURN WEAPONTYPE_DLC_COMBATSHOTGUN BREAK
        CASE 89 RETURN WEAPONTYPE_DLC_HEAVYRIFLE BREAK
        CASE 90 RETURN WEAPONTYPE_DLC_EMPLAUNCHER BREAK
        CASE 91 RETURN WEAPONTYPE_DLC_FERTILIZERCAN BREAK
        CASE 92 RETURN WEAPONTYPE_DLC_STUNGUNG_MP BREAK
    ENDSWITCH
    RETURN WEAPONTYPE_PISTOL
ENDFUNC

FUNC INT MENU_WEAPON_AMMO_FOR_CHOICE(INT choice)
    SWITCH choice
        CASE 0 RETURN 9999 BREAK
        CASE 1 RETURN 9999 BREAK
        CASE 2 RETURN 9999 BREAK
        CASE 3 RETURN 9999 BREAK
        CASE 4 RETURN 9999 BREAK
        CASE 5 RETURN 9999 BREAK
        CASE 6 RETURN 9999 BREAK
        CASE 7 RETURN 9999 BREAK
        CASE 8 RETURN 9999 BREAK
        CASE 9 RETURN 9999 BREAK
        CASE 10 RETURN 9999 BREAK
        CASE 11 RETURN 9999 BREAK
        CASE 12 RETURN 9999 BREAK
        CASE 13 RETURN 9999 BREAK
        CASE 14 RETURN 9999 BREAK
        CASE 15 RETURN 9999 BREAK
        CASE 16 RETURN 9999 BREAK
        CASE 17 RETURN 9999 BREAK
        CASE 18 RETURN 9999 BREAK
        CASE 19 RETURN 9999 BREAK
        CASE 20 RETURN 9999 BREAK
        CASE 21 RETURN 9999 BREAK
        CASE 22 RETURN 9999 BREAK
        CASE 23 RETURN 9999 BREAK
        CASE 24 RETURN 9999 BREAK
        CASE 25 RETURN 9999 BREAK
        CASE 26 RETURN 9999 BREAK
        CASE 27 RETURN 9999 BREAK
        CASE 28 RETURN 9999 BREAK
        CASE 29 RETURN 9999 BREAK
        CASE 30 RETURN 9999 BREAK
        CASE 31 RETURN 9999 BREAK
        CASE 32 RETURN 9999 BREAK
        CASE 33 RETURN 9999 BREAK
        CASE 34 RETURN 9999 BREAK
        CASE 35 RETURN 9999 BREAK
        CASE 36 RETURN 9999 BREAK
        CASE 37 RETURN 9999 BREAK
        CASE 38 RETURN 9999 BREAK
        CASE 39 RETURN 9999 BREAK
        CASE 40 RETURN 9999 BREAK
        CASE 41 RETURN 9999 BREAK
        CASE 42 RETURN 9999 BREAK
        CASE 43 RETURN 9999 BREAK
        CASE 44 RETURN 25 BREAK
        CASE 45 RETURN 9999 BREAK
        CASE 46 RETURN 25 BREAK
        CASE 47 RETURN 25 BREAK
        CASE 48 RETURN 25 BREAK
        CASE 49 RETURN 25 BREAK
        CASE 50 RETURN 9999 BREAK
        CASE 51 RETURN 25 BREAK
        CASE 52 RETURN 25 BREAK
        CASE 53 RETURN 25 BREAK
        CASE 54 RETURN 25 BREAK
        CASE 55 RETURN 25 BREAK
        CASE 56 RETURN 25 BREAK
        CASE 57 RETURN 25 BREAK
        CASE 58 RETURN 25 BREAK
        CASE 59 RETURN 25 BREAK
        CASE 60 RETURN 9999 BREAK
        CASE 61 RETURN 9999 BREAK
        CASE 62 RETURN 9999 BREAK
        CASE 63 RETURN 9999 BREAK
        CASE 64 RETURN 9999 BREAK
        CASE 65 RETURN 9999 BREAK
        CASE 66 RETURN 9999 BREAK
        CASE 67 RETURN 9999 BREAK
        CASE 68 RETURN 9999 BREAK
        CASE 69 RETURN 9999 BREAK
        CASE 70 RETURN 9999 BREAK
        CASE 71 RETURN 9999 BREAK
        CASE 72 RETURN 9999 BREAK
        CASE 73 RETURN 9999 BREAK
        CASE 74 RETURN 9999 BREAK
        CASE 75 RETURN 9999 BREAK
        CASE 76 RETURN 9999 BREAK
        CASE 77 RETURN 9999 BREAK
        CASE 78 RETURN 9999 BREAK
        CASE 79 RETURN 9999 BREAK
        CASE 80 RETURN 9999 BREAK
        CASE 81 RETURN 9999 BREAK
        CASE 82 RETURN 9999 BREAK
        CASE 83 RETURN 9999 BREAK
        CASE 84 RETURN 9999 BREAK
        CASE 85 RETURN 9999 BREAK
        CASE 86 RETURN 9999 BREAK
        CASE 87 RETURN 9999 BREAK
        CASE 88 RETURN 9999 BREAK
        CASE 89 RETURN 9999 BREAK
        CASE 90 RETURN 25 BREAK
        CASE 91 RETURN 9999 BREAK
        CASE 92 RETURN 9999 BREAK
    ENDSWITCH
    RETURN 9999
ENDFUNC

FUNC STRING MENU_WEAPON_NAME_FOR_CHOICE(INT choice)
    SWITCH choice
        CASE 0 RETURN "Pistol" BREAK
        CASE 1 RETURN "Combat Pistol" BREAK
        CASE 2 RETURN "AP Pistol" BREAK
        CASE 3 RETURN "Pistol .50" BREAK
        CASE 4 RETURN "SNS Pistol" BREAK
        CASE 5 RETURN "Heavy Pistol" BREAK
        CASE 6 RETURN "Vintage Pistol" BREAK
        CASE 7 RETURN "Marksman Pistol" BREAK
        CASE 8 RETURN "Heavy Revolver" BREAK
        CASE 9 RETURN "SNS Pistol Mk II" BREAK
        CASE 10 RETURN "Heavy Revolver Mk II" BREAK
        CASE 11 RETURN "Micro SMG" BREAK
        CASE 12 RETURN "SMG" BREAK
        CASE 13 RETURN "Assault SMG" BREAK
        CASE 14 RETURN "Combat PDW" BREAK
        CASE 15 RETURN "Machine Pistol" BREAK
        CASE 16 RETURN "Mini SMG" BREAK
        CASE 17 RETURN "Gusenberg Sweeper" BREAK
        CASE 18 RETURN "Assault Rifle" BREAK
        CASE 19 RETURN "Carbine Rifle" BREAK
        CASE 20 RETURN "Advanced Rifle" BREAK
        CASE 21 RETURN "Special Carbine" BREAK
        CASE 22 RETURN "Bullpup Rifle" BREAK
        CASE 23 RETURN "Compact Rifle" BREAK
        CASE 24 RETURN "Assault Rifle Mk II" BREAK
        CASE 25 RETURN "Carbine Rifle Mk II" BREAK
        CASE 26 RETURN "Special Carbine Mk II" BREAK
        CASE 27 RETURN "Machine Gun" BREAK
        CASE 28 RETURN "Combat MG" BREAK
        CASE 29 RETURN "Combat MG Mk II" BREAK
        CASE 30 RETURN "Pump Shotgun" BREAK
        CASE 31 RETURN "Sawed-Off Shotgun" BREAK
        CASE 32 RETURN "Assault Shotgun" BREAK
        CASE 33 RETURN "Bullpup Shotgun" BREAK
        CASE 34 RETURN "Heavy Shotgun" BREAK
        CASE 35 RETURN "Double Barrel Shotgun" BREAK
        CASE 36 RETURN "Sweeper Shotgun" BREAK
        CASE 37 RETURN "Pump Shotgun Mk II" BREAK
        CASE 38 RETURN "Sniper Rifle" BREAK
        CASE 39 RETURN "Heavy Sniper" BREAK
        CASE 40 RETURN "Marksman Rifle" BREAK
        CASE 41 RETURN "Heavy Sniper Mk II" BREAK
        CASE 42 RETURN "Marksman Rifle Mk II" BREAK
        CASE 43 RETURN "Grenade Launcher" BREAK
        CASE 44 RETURN "RPG" BREAK
        CASE 45 RETURN "Minigun" BREAK
        CASE 46 RETURN "Homing Launcher" BREAK
        CASE 47 RETURN "Compact Grenade Launcher" BREAK
        CASE 48 RETURN "Railgun" BREAK
        CASE 49 RETURN "Firework Launcher" BREAK
        CASE 50 RETURN "Musket" BREAK
        CASE 51 RETURN "Grenade" BREAK
        CASE 52 RETURN "Tear Gas" BREAK
        CASE 53 RETURN "BZ Gas" BREAK
        CASE 54 RETURN "Sticky Bomb" BREAK
        CASE 55 RETURN "Molotov" BREAK
        CASE 56 RETURN "Proximity Mine" BREAK
        CASE 57 RETURN "Pipe Bomb" BREAK
        CASE 58 RETURN "Snowball" BREAK
        CASE 59 RETURN "Flare Gun" BREAK
        CASE 60 RETURN "Stun Gun" BREAK
        CASE 61 RETURN "Fire Extinguisher" BREAK
        CASE 62 RETURN "Jerry Can" BREAK
        CASE 63 RETURN "Knife" BREAK
        CASE 64 RETURN "Nightstick" BREAK
        CASE 65 RETURN "Hammer" BREAK
        CASE 66 RETURN "Baseball Bat" BREAK
        CASE 67 RETURN "Crowbar" BREAK
        CASE 68 RETURN "Golf Club" BREAK
        CASE 69 RETURN "BOTTLE" BREAK
        CASE 70 RETURN "DAGGER" BREAK
        CASE 71 RETURN "Knuckle Duster" BREAK
        CASE 72 RETURN "MACHETE" BREAK
        CASE 73 RETURN "Switchblade" BREAK
        CASE 74 RETURN "Battle Axe" BREAK
        CASE 75 RETURN "HATCHET" BREAK
        CASE 76 RETURN "Pool Cue" BREAK
        CASE 77 RETURN "WRENCH" BREAK
        CASE 78 RETURN "Up-n-Atomizer" BREAK
        CASE 79 RETURN "Unholy Hellbringer" BREAK
        CASE 80 RETURN "Widowmaker" BREAK
        CASE 81 RETURN "Double Action Revolver" BREAK
        CASE 82 RETURN "Stone Hatchet" BREAK
        CASE 83 RETURN "Ceramic Pistol" BREAK
        CASE 84 RETURN "Hazardous Jerry Can" BREAK
        CASE 85 RETURN "Navy Revolver" BREAK
        CASE 86 RETURN "Perico Pistol" BREAK
        CASE 87 RETURN "Military Rifle" BREAK
        CASE 88 RETURN "Combat Shotgun" BREAK
        CASE 89 RETURN "Heavy Rifle" BREAK
        CASE 90 RETURN "Compact EMP Launcher" BREAK
        CASE 91 RETURN "Fertilizer Can" BREAK
        CASE 92 RETURN "Stun Gun MP" BREAK
    ENDSWITCH
    RETURN "Pistol"
ENDFUNC

PROC DRAW_MENU_WEAPON_SELECTOR(FLOAT y, BOOL selected)
    DRAW_OPTION(y, "Give Weapon:", MENU_WEAPON_NAME_FOR_CHOICE(g_weapon_choice), selected, 3)
ENDPROC

FUNC WEAPON_TYPE CURRENT_HELD_WEAPON()
    WEAPON_TYPE heldWeapon = WEAPONTYPE_UNARMED
    IF GET_CURRENT_PED_WEAPON(PLAYER_PED_ID(), heldWeapon, TRUE)
        RETURN heldWeapon
    ENDIF
    RETURN GET_SELECTED_PED_WEAPON(PLAYER_PED_ID())
ENDFUNC

FUNC BOOL HELD_WEAPON_EDITABLE()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF heldWeapon = WEAPONTYPE_UNARMED RETURN FALSE ENDIF
    IF NOT IS_WEAPON_VALID(heldWeapon) RETURN FALSE ENDIF
    IF NOT HAS_PED_GOT_WEAPON(PLAYER_PED_ID(), heldWeapon) RETURN FALSE ENDIF
    WEAPON_GROUP weaponGroup = GET_WEAPONTYPE_GROUP(heldWeapon)
    IF weaponGroup = WEAPONGROUP_MELEE RETURN FALSE ENDIF
    IF weaponGroup = WEAPONGROUP_THROWN RETURN FALSE ENDIF
    IF weaponGroup = WEAPONGROUP_PETROLCAN RETURN FALSE ENDIF
    IF weaponGroup = WEAPONGROUP_FIREEXTINGUISHER RETURN FALSE ENDIF
    IF weaponGroup = WEAPONGROUP_STUNGUN RETURN FALSE ENDIF
    IF heldWeapon = WEAPONTYPE_DLC_SNOWBALL RETURN FALSE ENDIF
    IF heldWeapon = WEAPONTYPE_BALL RETURN FALSE ENDIF
    IF heldWeapon = WEAPONTYPE_STUNGUN RETURN FALSE ENDIF
    IF heldWeapon = WEAPONTYPE_FIREEXTINGUISHER RETURN FALSE ENDIF
    IF heldWeapon = WEAPONTYPE_PETROLCAN RETURN FALSE ENDIF
    IF heldWeapon = WEAPONTYPE_FLARE RETURN FALSE ENDIF
    IF heldWeapon = GADGETTYPE_PARACHUTE RETURN FALSE ENDIF
    RETURN TRUE
ENDFUNC

PROC DRAW_WEAPON_UPGRADES_ENTRY(FLOAT y, BOOL selected)
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF NOT HAS_PED_GOT_WEAPON(PLAYER_PED_ID(), heldWeapon) OR heldWeapon = WEAPONTYPE_UNARMED
        DRAW_OPTION(y, "Weapon Upgrades", "NO WEAPON", selected, 0)
    ELIF NOT HELD_WEAPON_EDITABLE()
        DRAW_OPTION(y, "Weapon Upgrades", "BAD WEAPON", selected, 0)
    ELSE
        DRAW_OPTION(y, "Weapon Upgrades", "OPEN", selected, 2)
    ENDIF
ENDPROC

PROC REFILL_CURRENT_HELD_WEAPON()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    INT maxAmmo = 0
    IF NOT HAS_PED_GOT_WEAPON(PLAYER_PED_ID(), heldWeapon) EXIT ENDIF
    IF GET_MAX_AMMO(PLAYER_PED_ID(), heldWeapon, maxAmmo)
        SET_PED_AMMO(PLAYER_PED_ID(), heldWeapon, maxAmmo)
    ENDIF
ENDPROC

FUNC WEAPONCOMPONENT_TYPE HELD_WEAPON_MAG_COMPONENT()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF heldWeapon = WEAPONTYPE_PISTOL
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_PISTOL_CLIP_02) RETURN WEAPONCOMPONENT_PISTOL_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_PISTOL_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_COMBATPISTOL
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_COMBATPISTOL_CLIP_02) RETURN WEAPONCOMPONENT_COMBATPISTOL_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_COMBATPISTOL_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_APPISTOL
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_APPISTOL_CLIP_02) RETURN WEAPONCOMPONENT_APPISTOL_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_APPISTOL_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_MICROSMG
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_MICROSMG_CLIP_02) RETURN WEAPONCOMPONENT_MICROSMG_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_MICROSMG_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_SMG
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_SMG_CLIP_02) RETURN WEAPONCOMPONENT_SMG_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_SMG_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_ASSAULTRIFLE
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_ASSAULTRIFLE_CLIP_02) RETURN WEAPONCOMPONENT_ASSAULTRIFLE_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_ASSAULTRIFLE_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_CARBINERIFLE
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_CARBINERIFLE_CLIP_02) RETURN WEAPONCOMPONENT_CARBINERIFLE_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_CARBINERIFLE_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_ADVANCEDRIFLE
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_ADVANCEDRIFLE_CLIP_02) RETURN WEAPONCOMPONENT_ADVANCEDRIFLE_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_ADVANCEDRIFLE_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_MG
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_MG_CLIP_02) RETURN WEAPONCOMPONENT_MG_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_MG_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_COMBATMG
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_COMBATMG_CLIP_02) RETURN WEAPONCOMPONENT_COMBATMG_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_COMBATMG_CLIP_01
    ENDIF
    IF heldWeapon = WEAPONTYPE_ASSAULTSHOTGUN
        IF HAS_PED_GOT_WEAPON_COMPONENT(PLAYER_PED_ID(), heldWeapon, WEAPONCOMPONENT_ASSAULTSHOTGUN_CLIP_02) RETURN WEAPONCOMPONENT_ASSAULTSHOTGUN_CLIP_02 ENDIF
        RETURN WEAPONCOMPONENT_ASSAULTSHOTGUN_CLIP_01
    ENDIF
    RETURN WEAPONCOMPONENT_INVALID
ENDFUNC

FUNC WEAPONCOMPONENT_TYPE HELD_WEAPON_FLASHLIGHT_COMPONENT()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF heldWeapon = WEAPONTYPE_PISTOL RETURN WEAPONCOMPONENT_AT_PI_FLSH ENDIF
    IF heldWeapon = WEAPONTYPE_COMBATPISTOL RETURN WEAPONCOMPONENT_AT_PI_FLSH ENDIF
    IF heldWeapon = WEAPONTYPE_APPISTOL RETURN WEAPONCOMPONENT_AT_PI_FLSH ENDIF
    IF heldWeapon = WEAPONTYPE_MICROSMG RETURN WEAPONCOMPONENT_AT_PI_FLSH ENDIF
    IF heldWeapon = WEAPONTYPE_SMG RETURN WEAPONCOMPONENT_AT_AR_FLSH ENDIF
    IF heldWeapon = WEAPONTYPE_ASSAULTRIFLE RETURN WEAPONCOMPONENT_AT_AR_FLSH ENDIF
    IF heldWeapon = WEAPONTYPE_CARBINERIFLE RETURN WEAPONCOMPONENT_AT_AR_FLSH ENDIF
    IF heldWeapon = WEAPONTYPE_ADVANCEDRIFLE RETURN WEAPONCOMPONENT_AT_AR_FLSH ENDIF
    RETURN WEAPONCOMPONENT_INVALID
ENDFUNC

FUNC WEAPONCOMPONENT_TYPE HELD_WEAPON_SUPPRESSOR_COMPONENT()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF heldWeapon = WEAPONTYPE_PISTOL RETURN WEAPONCOMPONENT_AT_PI_SUPP ENDIF
    IF heldWeapon = WEAPONTYPE_COMBATPISTOL RETURN WEAPONCOMPONENT_AT_PI_SUPP ENDIF
    IF heldWeapon = WEAPONTYPE_APPISTOL RETURN WEAPONCOMPONENT_AT_PI_SUPP ENDIF
    IF heldWeapon = WEAPONTYPE_SMG RETURN WEAPONCOMPONENT_AT_PI_SUPP ENDIF
    IF heldWeapon = WEAPONTYPE_ASSAULTRIFLE RETURN WEAPONCOMPONENT_AT_AR_SUPP_02 ENDIF
    IF heldWeapon = WEAPONTYPE_CARBINERIFLE RETURN WEAPONCOMPONENT_AT_AR_SUPP ENDIF
    IF heldWeapon = WEAPONTYPE_ADVANCEDRIFLE RETURN WEAPONCOMPONENT_AT_AR_SUPP ENDIF
    RETURN WEAPONCOMPONENT_INVALID
ENDFUNC

FUNC WEAPONCOMPONENT_TYPE HELD_WEAPON_GRIP_COMPONENT()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF heldWeapon = WEAPONTYPE_ASSAULTRIFLE RETURN WEAPONCOMPONENT_AT_AR_AFGRIP ENDIF
    IF heldWeapon = WEAPONTYPE_CARBINERIFLE RETURN WEAPONCOMPONENT_AT_AR_AFGRIP ENDIF
    IF heldWeapon = WEAPONTYPE_ADVANCEDRIFLE RETURN WEAPONCOMPONENT_AT_AR_AFGRIP ENDIF
    IF heldWeapon = WEAPONTYPE_COMBATMG RETURN WEAPONCOMPONENT_AT_AR_AFGRIP ENDIF
    IF heldWeapon = WEAPONTYPE_ASSAULTSHOTGUN RETURN WEAPONCOMPONENT_AT_AR_AFGRIP ENDIF
    RETURN WEAPONCOMPONENT_INVALID
ENDFUNC

FUNC WEAPONCOMPONENT_TYPE HELD_WEAPON_SCOPE_COMPONENT()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF heldWeapon = WEAPONTYPE_MICROSMG RETURN WEAPONCOMPONENT_AT_SCOPE_MACRO ENDIF
    IF heldWeapon = WEAPONTYPE_ASSAULTRIFLE RETURN WEAPONCOMPONENT_AT_SCOPE_MACRO ENDIF
    IF heldWeapon = WEAPONTYPE_CARBINERIFLE RETURN WEAPONCOMPONENT_AT_SCOPE_MEDIUM ENDIF
    IF heldWeapon = WEAPONTYPE_ADVANCEDRIFLE RETURN WEAPONCOMPONENT_AT_SCOPE_SMALL ENDIF
    IF heldWeapon = WEAPONTYPE_COMBATMG RETURN WEAPONCOMPONENT_AT_SCOPE_MEDIUM ENDIF
    IF heldWeapon = WEAPONTYPE_SNIPERRIFLE RETURN WEAPONCOMPONENT_AT_SCOPE_LARGE ENDIF
    IF heldWeapon = WEAPONTYPE_HEAVYSNIPER RETURN WEAPONCOMPONENT_AT_SCOPE_MAX ENDIF
    IF heldWeapon = WEAPONTYPE_SMG RETURN WEAPONCOMPONENT_AT_SCOPE_MACRO_02 ENDIF
    IF heldWeapon = WEAPONTYPE_MG RETURN WEAPONCOMPONENT_AT_SCOPE_SMALL_02 ENDIF
    RETURN WEAPONCOMPONENT_INVALID
ENDFUNC

PROC TOGGLE_HELD_WEAPON_COMPONENT(WEAPONCOMPONENT_TYPE component)
    PED_INDEX playerPed = PLAYER_PED_ID()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    IF component = WEAPONCOMPONENT_INVALID EXIT ENDIF
    IF NOT HAS_PED_GOT_WEAPON(playerPed, heldWeapon) EXIT ENDIF
    IF HAS_PED_GOT_WEAPON_COMPONENT(playerPed, heldWeapon, component)
        REMOVE_WEAPON_COMPONENT_FROM_PED(playerPed, heldWeapon, component)
    ELSE
        GIVE_WEAPON_COMPONENT_TO_PED(playerPed, heldWeapon, component)
    ENDIF
ENDPROC

PROC DRAW_WEAPON_TINT_SELECTOR(FLOAT y, BOOL selected)
    PED_INDEX playerPed = PLAYER_PED_ID()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    INT tintCount = 0
    IF NOT HELD_WEAPON_EDITABLE()
        DRAW_OPTION(y, "Weapon Tint", "N/A", selected, 0)
        EXIT
    ENDIF
    tintCount = GET_WEAPON_TINT_COUNT(heldWeapon)
    IF tintCount <= 0
        DRAW_OPTION(y, "Weapon Tint", "N/A", selected, 0)
        EXIT
    ENDIF
    IF g_weapon_tint_choice < 0 g_weapon_tint_choice = 0 ENDIF
    IF g_weapon_tint_choice >= tintCount g_weapon_tint_choice = 0 ENDIF
    IF g_weapon_tint_choice = 0 DRAW_OPTION(y, "Weapon Tint", "< Default >", selected, 3) ENDIF
    IF g_weapon_tint_choice = 1 DRAW_OPTION(y, "Weapon Tint", "< Green >", selected, 3) ENDIF
    IF g_weapon_tint_choice = 2 DRAW_OPTION(y, "Weapon Tint", "< Gold >", selected, 3) ENDIF
    IF g_weapon_tint_choice = 3 DRAW_OPTION(y, "Weapon Tint", "< Pink >", selected, 3) ENDIF
    IF g_weapon_tint_choice = 4 DRAW_OPTION(y, "Weapon Tint", "< Army >", selected, 3) ENDIF
    IF g_weapon_tint_choice = 5 DRAW_OPTION(y, "Weapon Tint", "< LSPD >", selected, 3) ENDIF
    IF g_weapon_tint_choice = 6 DRAW_OPTION(y, "Weapon Tint", "< Orange >", selected, 3) ENDIF
    IF g_weapon_tint_choice = 7 DRAW_OPTION(y, "Weapon Tint", "< Platinum >", selected, 3) ENDIF
    SET_PED_WEAPON_TINT_INDEX(playerPed, heldWeapon, g_weapon_tint_choice)
ENDPROC

PROC DRAW_WEAPON_UPGRADES_ROW(INT index, FLOAT y)
    PED_INDEX playerPed = PLAYER_PED_ID()
    WEAPON_TYPE heldWeapon = CURRENT_HELD_WEAPON()
    WEAPONCOMPONENT_TYPE component = WEAPONCOMPONENT_INVALID
    IF index = 0 DRAW_OPTION(y, "Max Ammo (Held Weapon)", "APPLY", g_item = index, 2) ENDIF
    IF index = 1
        component = HELD_WEAPON_MAG_COMPONENT()
        IF component = WEAPONCOMPONENT_INVALID
            DRAW_OPTION(y, "Extended Mag", "N/A", g_item = index, 0)
        ELIF HAS_PED_GOT_WEAPON_COMPONENT(playerPed, heldWeapon, component)
            DRAW_OPTION(y, "Extended Mag", "ON", g_item = index, 1)
        ELSE
            DRAW_OPTION(y, "Extended Mag", "OFF", g_item = index, 0)
        ENDIF
    ENDIF
    IF index = 2
        component = HELD_WEAPON_FLASHLIGHT_COMPONENT()
        IF component = WEAPONCOMPONENT_INVALID
            DRAW_OPTION(y, "Flashlight", "N/A", g_item = index, 0)
        ELIF HAS_PED_GOT_WEAPON_COMPONENT(playerPed, heldWeapon, component)
            DRAW_OPTION(y, "Flashlight", "ON", g_item = index, 1)
        ELSE
            DRAW_OPTION(y, "Flashlight", "OFF", g_item = index, 0)
        ENDIF
    ENDIF
    IF index = 3
        component = HELD_WEAPON_SUPPRESSOR_COMPONENT()
        IF component = WEAPONCOMPONENT_INVALID
            DRAW_OPTION(y, "Suppressor", "N/A", g_item = index, 0)
        ELIF HAS_PED_GOT_WEAPON_COMPONENT(playerPed, heldWeapon, component)
            DRAW_OPTION(y, "Suppressor", "ON", g_item = index, 1)
        ELSE
            DRAW_OPTION(y, "Suppressor", "OFF", g_item = index, 0)
        ENDIF
    ENDIF
    IF index = 4
        component = HELD_WEAPON_GRIP_COMPONENT()
        IF component = WEAPONCOMPONENT_INVALID
            DRAW_OPTION(y, "Grip", "N/A", g_item = index, 0)
        ELIF HAS_PED_GOT_WEAPON_COMPONENT(playerPed, heldWeapon, component)
            DRAW_OPTION(y, "Grip", "ON", g_item = index, 1)
        ELSE
            DRAW_OPTION(y, "Grip", "OFF", g_item = index, 0)
        ENDIF
    ENDIF
    IF index = 5
        component = HELD_WEAPON_SCOPE_COMPONENT()
        IF component = WEAPONCOMPONENT_INVALID
            DRAW_OPTION(y, "Scope", "N/A", g_item = index, 0)
        ELIF HAS_PED_GOT_WEAPON_COMPONENT(playerPed, heldWeapon, component)
            DRAW_OPTION(y, "Scope", "ON", g_item = index, 1)
        ELSE
            DRAW_OPTION(y, "Scope", "OFF", g_item = index, 0)
        ENDIF
    ENDIF
    IF index = 6 DRAW_WEAPON_TINT_SELECTOR(y, g_item = index) ENDIF
ENDPROC

PROC DRAW_WEAPON_UPGRADES_PAGE()
    MENU_TEXT(g_menu_x - 0.130, 0.198, 0.270, 255, 255, 255, "WEAPON UPGRADES")
    DRAW_MENU_VERSION_TAG()
    INT index = g_weapon_upgrades_scroll
    INT row = 0
    WHILE row < 8 AND index < 7
        DRAW_WEAPON_UPGRADES_ROW(index, 0.268 + (TO_FLOAT(row) * ROW_H))
        index = index + 1
        row = row + 1
    ENDWHILE
ENDPROC

PROC DRAW_PROJECTILE_SELECTOR(FLOAT y, BOOL selected)
    SWITCH g_projectile_choice
        CASE 0 DRAW_OPTION(y, "Fired Asset:", "< Bullets >", selected, 3) BREAK
        CASE 1 DRAW_OPTION(y, "Fired Asset:", "< Random Cars >", selected, 3) BREAK
        CASE 2 DRAW_OPTION(y, "Fired Asset:", "< Random Animals >", selected, 3) BREAK
        CASE 3 DRAW_OPTION(y, "Fired Asset:", "< Random Peds >", selected, 3) BREAK
        CASE 4 DRAW_OPTION(y, "Fired Asset:", "< Random Aircraft >", selected, 3) BREAK
        CASE 5 DRAW_OPTION(y, "Fired Asset:", "< Random Boats >", selected, 3) BREAK
        CASE 6 DRAW_OPTION(y, "Fired Asset:", "< Random Bikes >", selected, 3) BREAK
        CASE 7 DRAW_OPTION(y, "Fired Asset:", "< Random Vehicles >", selected, 3) BREAK
    ENDSWITCH
ENDPROC

PROC CLEAR_PROJECTILE_SLOT()
    IF DOES_ENTITY_EXIST(g_projectile_vehicles[g_projectile_slot])
        SET_ENTITY_AS_MISSION_ENTITY(g_projectile_vehicles[g_projectile_slot], TRUE, TRUE)
        DELETE_VEHICLE(g_projectile_vehicles[g_projectile_slot])
    ENDIF
    IF DOES_ENTITY_EXIST(g_projectile_peds[g_projectile_slot])
        SET_ENTITY_AS_MISSION_ENTITY(g_projectile_peds[g_projectile_slot], TRUE, TRUE)
        DELETE_PED(g_projectile_peds[g_projectile_slot])
    ENDIF
    g_projectile_vehicles[g_projectile_slot] = NULL
    g_projectile_peds[g_projectile_slot] = NULL
ENDPROC

PROC SELECT_PROJECTILE_ASSET()
    g_pending_projectile_kind = 1
    SWITCH g_projectile_choice
        CASE 1
            SWITCH GET_RANDOM_INT_IN_RANGE(0, 4)
                CASE 0 g_pending_projectile_model = ADDER BREAK
                CASE 1 g_pending_projectile_model = BUFFALO BREAK
                CASE 2 g_pending_projectile_model = SULTAN BREAK
                CASE 3 g_pending_projectile_model = INFERNUS BREAK
            ENDSWITCH
        BREAK
        CASE 2
            g_pending_projectile_kind = 2
            SWITCH GET_RANDOM_INT_IN_RANGE(0, 3)
                CASE 0 g_pending_projectile_model = A_C_BOAR BREAK
                CASE 1 g_pending_projectile_model = A_C_COW BREAK
                CASE 2 g_pending_projectile_model = A_C_DEER BREAK
            ENDSWITCH
        BREAK
        CASE 3
            g_pending_projectile_kind = 2
            SWITCH GET_RANDOM_INT_IN_RANGE(0, 3)
                CASE 0 g_pending_projectile_model = A_M_M_SKATER_01 BREAK
                CASE 1 g_pending_projectile_model = S_M_Y_COP_01 BREAK
                CASE 2 g_pending_projectile_model = A_F_Y_HIPSTER_01 BREAK
            ENDSWITCH
        BREAK
        CASE 4
            SWITCH GET_RANDOM_INT_IN_RANGE(0, 3)
                CASE 0 g_pending_projectile_model = BUZZARD BREAK
                CASE 1 g_pending_projectile_model = DUSTER BREAK
                CASE 2 g_pending_projectile_model = HYDRA BREAK
            ENDSWITCH
        BREAK
        CASE 5
            SWITCH GET_RANDOM_INT_IN_RANGE(0, 3)
                CASE 0 g_pending_projectile_model = DINGHY BREAK
                CASE 1 g_pending_projectile_model = JETMAX BREAK
                CASE 2 g_pending_projectile_model = SEASHARK BREAK
            ENDSWITCH
        BREAK
        CASE 6
            SWITCH GET_RANDOM_INT_IN_RANGE(0, 3)
                CASE 0 g_pending_projectile_model = SANCHEZ BREAK
                CASE 1 g_pending_projectile_model = BATI BREAK
                CASE 2 g_pending_projectile_model = PCJ BREAK
            ENDSWITCH
        BREAK
        CASE 7
            SWITCH GET_RANDOM_INT_IN_RANGE(0, 6)
                CASE 0 g_pending_projectile_model = ADDER BREAK
                CASE 1 g_pending_projectile_model = A_C_BOAR g_pending_projectile_kind = 2 BREAK
                CASE 2 g_pending_projectile_model = A_M_M_SKATER_01 g_pending_projectile_kind = 2 BREAK
                CASE 3 g_pending_projectile_model = BUZZARD BREAK
                CASE 4 g_pending_projectile_model = DINGHY BREAK
                CASE 5 g_pending_projectile_model = SANCHEZ BREAK
            ENDSWITCH
        BREAK
    ENDSWITCH
ENDPROC

PROC START_PROJECTILE_SHOT()
    IF g_projectile_choice = 0 OR g_projectile_spawn_pending OR GET_GAME_TIMER() < g_next_projectile_time EXIT ENDIF
    SELECT_PROJECTILE_ASSET()
    IF NOT IS_MODEL_IN_CDIMAGE(g_pending_projectile_model) OR NOT IS_MODEL_VALID(g_pending_projectile_model) EXIT ENDIF
    REQUEST_MODEL(g_pending_projectile_model)
    g_projectile_spawn_pending = TRUE
    g_projectile_request_time = GET_GAME_TIMER()
ENDPROC

PROC FINISH_PROJECTILE_SHOT()
    PED_INDEX spawnedPed
    VEHICLE_INDEX spawnedVehicle
    VECTOR spawnPosition = GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(PLAYER_PED_ID(), <<0.0, 7.0, 1.0>>)
    VECTOR launchVelocity = GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(PLAYER_PED_ID(), <<0.0, 32.0, 1.0>>) - GET_ENTITY_COORDS(PLAYER_PED_ID())
    CLEAR_PROJECTILE_SLOT()
    IF g_pending_projectile_kind = 2
        spawnedPed = CREATE_PED(PEDTYPE_CIVMALE, g_pending_projectile_model, spawnPosition, GET_ENTITY_HEADING(PLAYER_PED_ID()), TRUE, FALSE)
        IF DOES_ENTITY_EXIST(spawnedPed)
            SET_ENTITY_VELOCITY(spawnedPed, launchVelocity)
            g_projectile_peds[g_projectile_slot] = spawnedPed
        ENDIF
    ELSE
        spawnedVehicle = CREATE_VEHICLE(g_pending_projectile_model, spawnPosition, GET_ENTITY_HEADING(PLAYER_PED_ID()), FALSE)
        IF DOES_ENTITY_EXIST(spawnedVehicle)
            SET_ENTITY_VELOCITY(spawnedVehicle, launchVelocity)
            g_projectile_vehicles[g_projectile_slot] = spawnedVehicle
        ENDIF
    ENDIF
    SET_MODEL_AS_NO_LONGER_NEEDED(g_pending_projectile_model)
    g_projectile_slot = g_projectile_slot + 1
    IF g_projectile_slot > 15 g_projectile_slot = 0 ENDIF
    g_projectile_spawn_pending = FALSE
    g_next_projectile_time = GET_GAME_TIMER() + 450
ENDPROC

PROC PROCESS_PROJECTILE_SHOT()
    IF g_projectile_spawn_pending
        IF HAS_MODEL_LOADED(g_pending_projectile_model)
            FINISH_PROJECTILE_SHOT()
        ELIF GET_GAME_TIMER() > g_projectile_request_time + 8000
            SET_MODEL_AS_NO_LONGER_NEEDED(g_pending_projectile_model)
            g_projectile_spawn_pending = FALSE
        ENDIF
    ELIF NOT g_open AND g_projectile_choice > 0 AND IS_PED_SHOOTING(PLAYER_PED_ID())
        START_PROJECTILE_SHOT()
    ENDIF
ENDPROC

PROC GIVE_SELECTED_MENU_WEAPON(PED_INDEX ped)
    IF g_weapon_choice < 0 OR g_weapon_choice >= MENU_WEAPON_COUNT() EXIT ENDIF
    GIVE_DELAYED_WEAPON_TO_PED(ped, MENU_WEAPON_FOR_CHOICE(g_weapon_choice), MENU_WEAPON_AMMO_FOR_CHOICE(g_weapon_choice), TRUE)
ENDPROC
