
FUNC INT PED_CHOICE_COUNT()
    RETURN 683
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_0(INT choice)
    SWITCH choice
        CASE 0 RETURN A_C_BOAR BREAK
        CASE 1 RETURN A_C_CAT_01 BREAK
        CASE 2 RETURN A_C_CHICKENHAWK BREAK
        CASE 3 RETURN A_C_CHIMP BREAK
        CASE 4 RETURN A_C_CHOP BREAK
        CASE 5 RETURN A_C_CORMORANT BREAK
        CASE 6 RETURN A_C_COW BREAK
        CASE 7 RETURN A_C_COYOTE BREAK
        CASE 8 RETURN A_C_CROW BREAK
        CASE 9 RETURN A_C_DEER BREAK
        CASE 10 RETURN A_C_DOLPHIN BREAK
        CASE 11 RETURN A_C_FISH BREAK
        CASE 12 RETURN A_C_HEN BREAK
        CASE 13 RETURN A_C_HUMPBACK BREAK
        CASE 14 RETURN A_C_HUSKY BREAK
        CASE 15 RETURN A_C_KILLERWHALE BREAK
        CASE 16 RETURN A_C_MTLION BREAK
        CASE 17 RETURN A_C_PIG BREAK
        CASE 18 RETURN A_C_PIGEON BREAK
        CASE 19 RETURN A_C_POODLE BREAK
        CASE 20 RETURN A_C_PUG BREAK
        CASE 21 RETURN A_C_RABBIT_01 BREAK
        CASE 22 RETURN A_C_RAT BREAK
        CASE 23 RETURN A_C_RETRIEVER BREAK
        CASE 24 RETURN A_C_RHESUS BREAK
        CASE 25 RETURN A_C_ROTTWEILER BREAK
        CASE 26 RETURN A_C_SEAGULL BREAK
        CASE 27 RETURN A_C_SHARKHAMMER BREAK
        CASE 28 RETURN A_C_SHARKTIGER BREAK
        CASE 29 RETURN A_C_SHEPHERD BREAK
        CASE 30 RETURN A_C_STINGRAY BREAK
        CASE 31 RETURN A_C_WESTY BREAK
        CASE 32 RETURN A_F_M_BEACH_01 BREAK
        CASE 33 RETURN A_F_M_BEVHILLS_01 BREAK
        CASE 34 RETURN A_F_M_BEVHILLS_02 BREAK
        CASE 35 RETURN A_F_M_BODYBUILD_01 BREAK
        CASE 36 RETURN A_F_M_BUSINESS_02 BREAK
        CASE 37 RETURN A_F_M_DOWNTOWN_01 BREAK
        CASE 38 RETURN A_F_M_EASTSA_01 BREAK
        CASE 39 RETURN A_F_M_EASTSA_02 BREAK
        CASE 40 RETURN A_F_M_FATBLA_01 BREAK
        CASE 41 RETURN A_F_M_FATCULT_01 BREAK
        CASE 42 RETURN A_F_M_FATWHITE_01 BREAK
        CASE 43 RETURN A_F_M_KTOWN_01 BREAK
        CASE 44 RETURN A_F_M_KTOWN_02 BREAK
        CASE 45 RETURN A_F_M_PROLHOST_01 BREAK
        CASE 46 RETURN A_F_M_SALTON_01 BREAK
        CASE 47 RETURN A_F_M_SKIDROW_01 BREAK
        CASE 48 RETURN A_F_M_SOUCENTMC_01 BREAK
        CASE 49 RETURN A_F_M_SOUCENT_01 BREAK
        CASE 50 RETURN A_F_M_SOUCENT_02 BREAK
        CASE 51 RETURN A_F_M_TOURIST_01 BREAK
        CASE 52 RETURN A_F_M_TRAMPBEAC_01 BREAK
        CASE 53 RETURN A_F_M_TRAMP_01 BREAK
        CASE 54 RETURN A_F_O_GENSTREET_01 BREAK
        CASE 55 RETURN A_F_O_INDIAN_01 BREAK
        CASE 56 RETURN A_F_O_KTOWN_01 BREAK
        CASE 57 RETURN A_F_O_SALTON_01 BREAK
        CASE 58 RETURN A_F_O_SOUCENT_01 BREAK
        CASE 59 RETURN A_F_O_SOUCENT_02 BREAK
        CASE 60 RETURN A_F_Y_BEACH_01 BREAK
        CASE 61 RETURN A_F_Y_BEVHILLS_01 BREAK
        CASE 62 RETURN A_F_Y_BEVHILLS_02 BREAK
        CASE 63 RETURN A_F_Y_BEVHILLS_03 BREAK
        CASE 64 RETURN A_F_Y_BEVHILLS_04 BREAK
        CASE 65 RETURN A_F_Y_BUSINESS_01 BREAK
        CASE 66 RETURN A_F_Y_BUSINESS_02 BREAK
        CASE 67 RETURN A_F_Y_BUSINESS_03 BREAK
        CASE 68 RETURN A_F_Y_BUSINESS_04 BREAK
        CASE 69 RETURN A_F_Y_EASTSA_01 BREAK
        CASE 70 RETURN A_F_Y_EASTSA_02 BREAK
        CASE 71 RETURN A_F_Y_EASTSA_03 BREAK
        CASE 72 RETURN A_F_Y_EPSILON_01 BREAK
        CASE 73 RETURN A_F_Y_FITNESS_01 BREAK
        CASE 74 RETURN A_F_Y_FITNESS_02 BREAK
        CASE 75 RETURN A_F_Y_GENHOT_01 BREAK
        CASE 76 RETURN A_F_Y_GOLFER_01 BREAK
        CASE 77 RETURN A_F_Y_HIKER_01 BREAK
        CASE 78 RETURN A_F_Y_HIPPIE_01 BREAK
        CASE 79 RETURN A_F_Y_HIPSTER_01 BREAK
        CASE 80 RETURN A_F_Y_HIPSTER_02 BREAK
        CASE 81 RETURN A_F_Y_HIPSTER_03 BREAK
        CASE 82 RETURN A_F_Y_HIPSTER_04 BREAK
        CASE 83 RETURN A_F_Y_INDIAN_01 BREAK
        CASE 84 RETURN A_F_Y_JUGGALO_01 BREAK
        CASE 85 RETURN A_F_Y_RUNNER_01 BREAK
        CASE 86 RETURN A_F_Y_RURMETH_01 BREAK
        CASE 87 RETURN A_F_Y_SCDRESSY_01 BREAK
        CASE 88 RETURN A_F_Y_SKATER_01 BREAK
        CASE 89 RETURN A_F_Y_SOUCENT_01 BREAK
        CASE 90 RETURN A_F_Y_SOUCENT_02 BREAK
        CASE 91 RETURN A_F_Y_SOUCENT_03 BREAK
        CASE 92 RETURN A_F_Y_TENNIS_01 BREAK
        CASE 93 RETURN A_F_Y_TOPLESS_01 BREAK
        CASE 94 RETURN A_F_Y_TOURIST_01 BREAK
        CASE 95 RETURN A_F_Y_TOURIST_02 BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_0(INT choice)
    SWITCH choice
        CASE 0 RETURN "A_C_BOAR" BREAK
        CASE 1 RETURN "A_C_CAT_01" BREAK
        CASE 2 RETURN "A_C_CHICKENHAWK" BREAK
        CASE 3 RETURN "A_C_CHIMP" BREAK
        CASE 4 RETURN "A_C_CHOP" BREAK
        CASE 5 RETURN "A_C_CORMORANT" BREAK
        CASE 6 RETURN "A_C_COW" BREAK
        CASE 7 RETURN "A_C_COYOTE" BREAK
        CASE 8 RETURN "A_C_CROW" BREAK
        CASE 9 RETURN "A_C_DEER" BREAK
        CASE 10 RETURN "A_C_DOLPHIN" BREAK
        CASE 11 RETURN "A_C_FISH" BREAK
        CASE 12 RETURN "A_C_HEN" BREAK
        CASE 13 RETURN "A_C_HUMPBACK" BREAK
        CASE 14 RETURN "A_C_HUSKY" BREAK
        CASE 15 RETURN "A_C_KILLERWHALE" BREAK
        CASE 16 RETURN "A_C_MTLION" BREAK
        CASE 17 RETURN "A_C_PIG" BREAK
        CASE 18 RETURN "A_C_PIGEON" BREAK
        CASE 19 RETURN "A_C_POODLE" BREAK
        CASE 20 RETURN "A_C_PUG" BREAK
        CASE 21 RETURN "A_C_RABBIT_01" BREAK
        CASE 22 RETURN "A_C_RAT" BREAK
        CASE 23 RETURN "A_C_RETRIEVER" BREAK
        CASE 24 RETURN "A_C_RHESUS" BREAK
        CASE 25 RETURN "A_C_ROTTWEILER" BREAK
        CASE 26 RETURN "A_C_SEAGULL" BREAK
        CASE 27 RETURN "A_C_SHARKHAMMER" BREAK
        CASE 28 RETURN "A_C_SHARKTIGER" BREAK
        CASE 29 RETURN "A_C_SHEPHERD" BREAK
        CASE 30 RETURN "A_C_STINGRAY" BREAK
        CASE 31 RETURN "A_C_WESTY" BREAK
        CASE 32 RETURN "A_F_M_BEACH_01" BREAK
        CASE 33 RETURN "A_F_M_BEVHILLS_01" BREAK
        CASE 34 RETURN "A_F_M_BEVHILLS_02" BREAK
        CASE 35 RETURN "A_F_M_BODYBUILD_01" BREAK
        CASE 36 RETURN "A_F_M_BUSINESS_02" BREAK
        CASE 37 RETURN "A_F_M_DOWNTOWN_01" BREAK
        CASE 38 RETURN "A_F_M_EASTSA_01" BREAK
        CASE 39 RETURN "A_F_M_EASTSA_02" BREAK
        CASE 40 RETURN "A_F_M_FATBLA_01" BREAK
        CASE 41 RETURN "A_F_M_FATCULT_01" BREAK
        CASE 42 RETURN "A_F_M_FATWHITE_01" BREAK
        CASE 43 RETURN "A_F_M_KTOWN_01" BREAK
        CASE 44 RETURN "A_F_M_KTOWN_02" BREAK
        CASE 45 RETURN "A_F_M_PROLHOST_01" BREAK
        CASE 46 RETURN "A_F_M_SALTON_01" BREAK
        CASE 47 RETURN "A_F_M_SKIDROW_01" BREAK
        CASE 48 RETURN "A_F_M_SOUCENTMC_01" BREAK
        CASE 49 RETURN "A_F_M_SOUCENT_01" BREAK
        CASE 50 RETURN "A_F_M_SOUCENT_02" BREAK
        CASE 51 RETURN "A_F_M_TOURIST_01" BREAK
        CASE 52 RETURN "A_F_M_TRAMPBEAC_01" BREAK
        CASE 53 RETURN "A_F_M_TRAMP_01" BREAK
        CASE 54 RETURN "A_F_O_GENSTREET_01" BREAK
        CASE 55 RETURN "A_F_O_INDIAN_01" BREAK
        CASE 56 RETURN "A_F_O_KTOWN_01" BREAK
        CASE 57 RETURN "A_F_O_SALTON_01" BREAK
        CASE 58 RETURN "A_F_O_SOUCENT_01" BREAK
        CASE 59 RETURN "A_F_O_SOUCENT_02" BREAK
        CASE 60 RETURN "A_F_Y_BEACH_01" BREAK
        CASE 61 RETURN "A_F_Y_BEVHILLS_01" BREAK
        CASE 62 RETURN "A_F_Y_BEVHILLS_02" BREAK
        CASE 63 RETURN "A_F_Y_BEVHILLS_03" BREAK
        CASE 64 RETURN "A_F_Y_BEVHILLS_04" BREAK
        CASE 65 RETURN "A_F_Y_BUSINESS_01" BREAK
        CASE 66 RETURN "A_F_Y_BUSINESS_02" BREAK
        CASE 67 RETURN "A_F_Y_BUSINESS_03" BREAK
        CASE 68 RETURN "A_F_Y_BUSINESS_04" BREAK
        CASE 69 RETURN "A_F_Y_EASTSA_01" BREAK
        CASE 70 RETURN "A_F_Y_EASTSA_02" BREAK
        CASE 71 RETURN "A_F_Y_EASTSA_03" BREAK
        CASE 72 RETURN "A_F_Y_EPSILON_01" BREAK
        CASE 73 RETURN "A_F_Y_FITNESS_01" BREAK
        CASE 74 RETURN "A_F_Y_FITNESS_02" BREAK
        CASE 75 RETURN "A_F_Y_GENHOT_01" BREAK
        CASE 76 RETURN "A_F_Y_GOLFER_01" BREAK
        CASE 77 RETURN "A_F_Y_HIKER_01" BREAK
        CASE 78 RETURN "A_F_Y_HIPPIE_01" BREAK
        CASE 79 RETURN "A_F_Y_HIPSTER_01" BREAK
        CASE 80 RETURN "A_F_Y_HIPSTER_02" BREAK
        CASE 81 RETURN "A_F_Y_HIPSTER_03" BREAK
        CASE 82 RETURN "A_F_Y_HIPSTER_04" BREAK
        CASE 83 RETURN "A_F_Y_INDIAN_01" BREAK
        CASE 84 RETURN "A_F_Y_JUGGALO_01" BREAK
        CASE 85 RETURN "A_F_Y_RUNNER_01" BREAK
        CASE 86 RETURN "A_F_Y_RURMETH_01" BREAK
        CASE 87 RETURN "A_F_Y_SCDRESSY_01" BREAK
        CASE 88 RETURN "A_F_Y_SKATER_01" BREAK
        CASE 89 RETURN "A_F_Y_SOUCENT_01" BREAK
        CASE 90 RETURN "A_F_Y_SOUCENT_02" BREAK
        CASE 91 RETURN "A_F_Y_SOUCENT_03" BREAK
        CASE 92 RETURN "A_F_Y_TENNIS_01" BREAK
        CASE 93 RETURN "A_F_Y_TOPLESS_01" BREAK
        CASE 94 RETURN "A_F_Y_TOURIST_01" BREAK
        CASE 95 RETURN "A_F_Y_TOURIST_02" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_1(INT choice)
    SWITCH choice
        CASE 0 RETURN A_F_Y_VINEWOOD_01 BREAK
        CASE 1 RETURN A_F_Y_VINEWOOD_02 BREAK
        CASE 2 RETURN A_F_Y_VINEWOOD_03 BREAK
        CASE 3 RETURN A_F_Y_VINEWOOD_04 BREAK
        CASE 4 RETURN A_F_Y_YOGA_01 BREAK
        CASE 5 RETURN A_M_M_ACULT_01 BREAK
        CASE 6 RETURN A_M_M_AFRIAMER_01 BREAK
        CASE 7 RETURN A_M_M_BEACH_01 BREAK
        CASE 8 RETURN A_M_M_BEACH_02 BREAK
        CASE 9 RETURN A_M_M_BEVHILLS_01 BREAK
        CASE 10 RETURN A_M_M_BEVHILLS_02 BREAK
        CASE 11 RETURN A_M_M_BUSINESS_01 BREAK
        CASE 12 RETURN A_M_M_EASTSA_01 BREAK
        CASE 13 RETURN A_M_M_EASTSA_02 BREAK
        CASE 14 RETURN A_M_M_FARMER_01 BREAK
        CASE 15 RETURN A_M_M_FATLATIN_01 BREAK
        CASE 16 RETURN A_M_M_GENFAT_01 BREAK
        CASE 17 RETURN A_M_M_GENFAT_02 BREAK
        CASE 18 RETURN A_M_M_GOLFER_01 BREAK
        CASE 19 RETURN A_M_M_HASJEW_01 BREAK
        CASE 20 RETURN A_M_M_HILLBILLY_01 BREAK
        CASE 21 RETURN A_M_M_HILLBILLY_02 BREAK
        CASE 22 RETURN A_M_M_INDIAN_01 BREAK
        CASE 23 RETURN A_M_M_KTOWN_01 BREAK
        CASE 24 RETURN A_M_M_MALIBU_01 BREAK
        CASE 25 RETURN A_M_M_MEXCNTRY_01 BREAK
        CASE 26 RETURN A_M_M_MEXLABOR_01 BREAK
        CASE 27 RETURN A_M_M_OG_BOSS_01 BREAK
        CASE 28 RETURN A_M_M_PAPARAZZI_01 BREAK
        CASE 29 RETURN A_M_M_POLYNESIAN_01 BREAK
        CASE 30 RETURN A_M_M_PROLHOST_01 BREAK
        CASE 31 RETURN A_M_M_RURMETH_01 BREAK
        CASE 32 RETURN A_M_M_SALTON_01 BREAK
        CASE 33 RETURN A_M_M_SALTON_02 BREAK
        CASE 34 RETURN A_M_M_SALTON_03 BREAK
        CASE 35 RETURN A_M_M_SALTON_04 BREAK
        CASE 36 RETURN A_M_M_SKATER_01 BREAK
        CASE 37 RETURN A_M_M_SKIDROW_01 BREAK
        CASE 38 RETURN A_M_M_SOCENLAT_01 BREAK
        CASE 39 RETURN A_M_M_SOUCENT_01 BREAK
        CASE 40 RETURN A_M_M_SOUCENT_02 BREAK
        CASE 41 RETURN A_M_M_SOUCENT_03 BREAK
        CASE 42 RETURN A_M_M_SOUCENT_04 BREAK
        CASE 43 RETURN A_M_M_STLAT_02 BREAK
        CASE 44 RETURN A_M_M_TENNIS_01 BREAK
        CASE 45 RETURN A_M_M_TOURIST_01 BREAK
        CASE 46 RETURN A_M_M_TRAMPBEAC_01 BREAK
        CASE 47 RETURN A_M_M_TRAMP_01 BREAK
        CASE 48 RETURN A_M_M_TRANVEST_01 BREAK
        CASE 49 RETURN A_M_M_TRANVEST_02 BREAK
        CASE 50 RETURN A_M_O_ACULT_01 BREAK
        CASE 51 RETURN A_M_O_ACULT_02 BREAK
        CASE 52 RETURN A_M_O_BEACH_01 BREAK
        CASE 53 RETURN A_M_O_GENSTREET_01 BREAK
        CASE 54 RETURN A_M_O_KTOWN_01 BREAK
        CASE 55 RETURN A_M_O_SALTON_01 BREAK
        CASE 56 RETURN A_M_O_SOUCENT_01 BREAK
        CASE 57 RETURN A_M_O_SOUCENT_02 BREAK
        CASE 58 RETURN A_M_O_SOUCENT_03 BREAK
        CASE 59 RETURN A_M_O_TRAMP_01 BREAK
        CASE 60 RETURN A_M_Y_ACULT_01 BREAK
        CASE 61 RETURN A_M_Y_ACULT_02 BREAK
        CASE 62 RETURN A_M_Y_BEACHVESP_01 BREAK
        CASE 63 RETURN A_M_Y_BEACHVESP_02 BREAK
        CASE 64 RETURN A_M_Y_BEACH_01 BREAK
        CASE 65 RETURN A_M_Y_BEACH_02 BREAK
        CASE 66 RETURN A_M_Y_BEACH_03 BREAK
        CASE 67 RETURN A_M_Y_BEVHILLS_01 BREAK
        CASE 68 RETURN A_M_Y_BEVHILLS_02 BREAK
        CASE 69 RETURN A_M_Y_BREAKDANCE_01 BREAK
        CASE 70 RETURN A_M_Y_BUSICAS_01 BREAK
        CASE 71 RETURN A_M_Y_BUSINESS_01 BREAK
        CASE 72 RETURN A_M_Y_BUSINESS_02 BREAK
        CASE 73 RETURN A_M_Y_BUSINESS_03 BREAK
        CASE 74 RETURN A_M_Y_CYCLIST_01 BREAK
        CASE 75 RETURN A_M_Y_DHILL_01 BREAK
        CASE 76 RETURN A_M_Y_DOWNTOWN_01 BREAK
        CASE 77 RETURN A_M_Y_EASTSA_01 BREAK
        CASE 78 RETURN A_M_Y_EASTSA_02 BREAK
        CASE 79 RETURN A_M_Y_EPSILON_01 BREAK
        CASE 80 RETURN A_M_Y_EPSILON_02 BREAK
        CASE 81 RETURN A_M_Y_GAY_01 BREAK
        CASE 82 RETURN A_M_Y_GAY_02 BREAK
        CASE 83 RETURN A_M_Y_GENSTREET_01 BREAK
        CASE 84 RETURN A_M_Y_GENSTREET_02 BREAK
        CASE 85 RETURN A_M_Y_GOLFER_01 BREAK
        CASE 86 RETURN A_M_Y_HASJEW_01 BREAK
        CASE 87 RETURN A_M_Y_HIKER_01 BREAK
        CASE 88 RETURN A_M_Y_HIPPY_01 BREAK
        CASE 89 RETURN A_M_Y_HIPSTER_01 BREAK
        CASE 90 RETURN A_M_Y_HIPSTER_02 BREAK
        CASE 91 RETURN A_M_Y_HIPSTER_03 BREAK
        CASE 92 RETURN A_M_Y_INDIAN_01 BREAK
        CASE 93 RETURN A_M_Y_JETSKI_01 BREAK
        CASE 94 RETURN A_M_Y_JUGGALO_01 BREAK
        CASE 95 RETURN A_M_Y_KTOWN_01 BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_1(INT choice)
    SWITCH choice
        CASE 0 RETURN "A_F_Y_VINEWOOD_01" BREAK
        CASE 1 RETURN "A_F_Y_VINEWOOD_02" BREAK
        CASE 2 RETURN "A_F_Y_VINEWOOD_03" BREAK
        CASE 3 RETURN "A_F_Y_VINEWOOD_04" BREAK
        CASE 4 RETURN "A_F_Y_YOGA_01" BREAK
        CASE 5 RETURN "A_M_M_ACULT_01" BREAK
        CASE 6 RETURN "A_M_M_AFRIAMER_01" BREAK
        CASE 7 RETURN "A_M_M_BEACH_01" BREAK
        CASE 8 RETURN "A_M_M_BEACH_02" BREAK
        CASE 9 RETURN "A_M_M_BEVHILLS_01" BREAK
        CASE 10 RETURN "A_M_M_BEVHILLS_02" BREAK
        CASE 11 RETURN "A_M_M_BUSINESS_01" BREAK
        CASE 12 RETURN "A_M_M_EASTSA_01" BREAK
        CASE 13 RETURN "A_M_M_EASTSA_02" BREAK
        CASE 14 RETURN "A_M_M_FARMER_01" BREAK
        CASE 15 RETURN "A_M_M_FATLATIN_01" BREAK
        CASE 16 RETURN "A_M_M_GENFAT_01" BREAK
        CASE 17 RETURN "A_M_M_GENFAT_02" BREAK
        CASE 18 RETURN "A_M_M_GOLFER_01" BREAK
        CASE 19 RETURN "A_M_M_HASJEW_01" BREAK
        CASE 20 RETURN "A_M_M_HILLBILLY_01" BREAK
        CASE 21 RETURN "A_M_M_HILLBILLY_02" BREAK
        CASE 22 RETURN "A_M_M_INDIAN_01" BREAK
        CASE 23 RETURN "A_M_M_KTOWN_01" BREAK
        CASE 24 RETURN "A_M_M_MALIBU_01" BREAK
        CASE 25 RETURN "A_M_M_MEXCNTRY_01" BREAK
        CASE 26 RETURN "A_M_M_MEXLABOR_01" BREAK
        CASE 27 RETURN "A_M_M_OG_BOSS_01" BREAK
        CASE 28 RETURN "A_M_M_PAPARAZZI_01" BREAK
        CASE 29 RETURN "A_M_M_POLYNESIAN_01" BREAK
        CASE 30 RETURN "A_M_M_PROLHOST_01" BREAK
        CASE 31 RETURN "A_M_M_RURMETH_01" BREAK
        CASE 32 RETURN "A_M_M_SALTON_01" BREAK
        CASE 33 RETURN "A_M_M_SALTON_02" BREAK
        CASE 34 RETURN "A_M_M_SALTON_03" BREAK
        CASE 35 RETURN "A_M_M_SALTON_04" BREAK
        CASE 36 RETURN "A_M_M_SKATER_01" BREAK
        CASE 37 RETURN "A_M_M_SKIDROW_01" BREAK
        CASE 38 RETURN "A_M_M_SOCENLAT_01" BREAK
        CASE 39 RETURN "A_M_M_SOUCENT_01" BREAK
        CASE 40 RETURN "A_M_M_SOUCENT_02" BREAK
        CASE 41 RETURN "A_M_M_SOUCENT_03" BREAK
        CASE 42 RETURN "A_M_M_SOUCENT_04" BREAK
        CASE 43 RETURN "A_M_M_STLAT_02" BREAK
        CASE 44 RETURN "A_M_M_TENNIS_01" BREAK
        CASE 45 RETURN "A_M_M_TOURIST_01" BREAK
        CASE 46 RETURN "A_M_M_TRAMPBEAC_01" BREAK
        CASE 47 RETURN "A_M_M_TRAMP_01" BREAK
        CASE 48 RETURN "A_M_M_TRANVEST_01" BREAK
        CASE 49 RETURN "A_M_M_TRANVEST_02" BREAK
        CASE 50 RETURN "A_M_O_ACULT_01" BREAK
        CASE 51 RETURN "A_M_O_ACULT_02" BREAK
        CASE 52 RETURN "A_M_O_BEACH_01" BREAK
        CASE 53 RETURN "A_M_O_GENSTREET_01" BREAK
        CASE 54 RETURN "A_M_O_KTOWN_01" BREAK
        CASE 55 RETURN "A_M_O_SALTON_01" BREAK
        CASE 56 RETURN "A_M_O_SOUCENT_01" BREAK
        CASE 57 RETURN "A_M_O_SOUCENT_02" BREAK
        CASE 58 RETURN "A_M_O_SOUCENT_03" BREAK
        CASE 59 RETURN "A_M_O_TRAMP_01" BREAK
        CASE 60 RETURN "A_M_Y_ACULT_01" BREAK
        CASE 61 RETURN "A_M_Y_ACULT_02" BREAK
        CASE 62 RETURN "A_M_Y_BEACHVESP_01" BREAK
        CASE 63 RETURN "A_M_Y_BEACHVESP_02" BREAK
        CASE 64 RETURN "A_M_Y_BEACH_01" BREAK
        CASE 65 RETURN "A_M_Y_BEACH_02" BREAK
        CASE 66 RETURN "A_M_Y_BEACH_03" BREAK
        CASE 67 RETURN "A_M_Y_BEVHILLS_01" BREAK
        CASE 68 RETURN "A_M_Y_BEVHILLS_02" BREAK
        CASE 69 RETURN "A_M_Y_BREAKDANCE_01" BREAK
        CASE 70 RETURN "A_M_Y_BUSICAS_01" BREAK
        CASE 71 RETURN "A_M_Y_BUSINESS_01" BREAK
        CASE 72 RETURN "A_M_Y_BUSINESS_02" BREAK
        CASE 73 RETURN "A_M_Y_BUSINESS_03" BREAK
        CASE 74 RETURN "A_M_Y_CYCLIST_01" BREAK
        CASE 75 RETURN "A_M_Y_DHILL_01" BREAK
        CASE 76 RETURN "A_M_Y_DOWNTOWN_01" BREAK
        CASE 77 RETURN "A_M_Y_EASTSA_01" BREAK
        CASE 78 RETURN "A_M_Y_EASTSA_02" BREAK
        CASE 79 RETURN "A_M_Y_EPSILON_01" BREAK
        CASE 80 RETURN "A_M_Y_EPSILON_02" BREAK
        CASE 81 RETURN "A_M_Y_GAY_01" BREAK
        CASE 82 RETURN "A_M_Y_GAY_02" BREAK
        CASE 83 RETURN "A_M_Y_GENSTREET_01" BREAK
        CASE 84 RETURN "A_M_Y_GENSTREET_02" BREAK
        CASE 85 RETURN "A_M_Y_GOLFER_01" BREAK
        CASE 86 RETURN "A_M_Y_HASJEW_01" BREAK
        CASE 87 RETURN "A_M_Y_HIKER_01" BREAK
        CASE 88 RETURN "A_M_Y_HIPPY_01" BREAK
        CASE 89 RETURN "A_M_Y_HIPSTER_01" BREAK
        CASE 90 RETURN "A_M_Y_HIPSTER_02" BREAK
        CASE 91 RETURN "A_M_Y_HIPSTER_03" BREAK
        CASE 92 RETURN "A_M_Y_INDIAN_01" BREAK
        CASE 93 RETURN "A_M_Y_JETSKI_01" BREAK
        CASE 94 RETURN "A_M_Y_JUGGALO_01" BREAK
        CASE 95 RETURN "A_M_Y_KTOWN_01" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_2(INT choice)
    SWITCH choice
        CASE 0 RETURN A_M_Y_KTOWN_02 BREAK
        CASE 1 RETURN A_M_Y_LATINO_01 BREAK
        CASE 2 RETURN A_M_Y_METHHEAD_01 BREAK
        CASE 3 RETURN A_M_Y_MEXTHUG_01 BREAK
        CASE 4 RETURN A_M_Y_MOTOX_01 BREAK
        CASE 5 RETURN A_M_Y_MOTOX_02 BREAK
        CASE 6 RETURN A_M_Y_MUSCLBEAC_01 BREAK
        CASE 7 RETURN A_M_Y_MUSCLBEAC_02 BREAK
        CASE 8 RETURN A_M_Y_POLYNESIAN_01 BREAK
        CASE 9 RETURN A_M_Y_ROADCYC_01 BREAK
        CASE 10 RETURN A_M_Y_RUNNER_01 BREAK
        CASE 11 RETURN A_M_Y_RUNNER_02 BREAK
        CASE 12 RETURN A_M_Y_SALTON_01 BREAK
        CASE 13 RETURN A_M_Y_SKATER_01 BREAK
        CASE 14 RETURN A_M_Y_SKATER_02 BREAK
        CASE 15 RETURN A_M_Y_SOUCENT_01 BREAK
        CASE 16 RETURN A_M_Y_SOUCENT_02 BREAK
        CASE 17 RETURN A_M_Y_SOUCENT_03 BREAK
        CASE 18 RETURN A_M_Y_SOUCENT_04 BREAK
        CASE 19 RETURN A_M_Y_STBLA_01 BREAK
        CASE 20 RETURN A_M_Y_STBLA_02 BREAK
        CASE 21 RETURN A_M_Y_STLAT_01 BREAK
        CASE 22 RETURN A_M_Y_STWHI_01 BREAK
        CASE 23 RETURN A_M_Y_STWHI_02 BREAK
        CASE 24 RETURN A_M_Y_SUNBATHE_01 BREAK
        CASE 25 RETURN A_M_Y_SURFER_01 BREAK
        CASE 26 RETURN A_M_Y_VINDOUCHE_01 BREAK
        CASE 27 RETURN A_M_Y_VINEWOOD_01 BREAK
        CASE 28 RETURN A_M_Y_VINEWOOD_02 BREAK
        CASE 29 RETURN A_M_Y_VINEWOOD_03 BREAK
        CASE 30 RETURN A_M_Y_VINEWOOD_04 BREAK
        CASE 31 RETURN A_M_Y_YOGA_01 BREAK
        CASE 32 RETURN CSB_ABIGAIL BREAK
        CASE 33 RETURN CSB_ANITA BREAK
        CASE 34 RETURN CSB_ANTON BREAK
        CASE 35 RETURN CSB_BALLASOG BREAK
        CASE 36 RETURN CSB_BRIDE BREAK
        CASE 37 RETURN CSB_BURGERDRUG BREAK
        CASE 38 RETURN CSB_CAR3GUY1 BREAK
        CASE 39 RETURN CSB_CAR3GUY2 BREAK
        CASE 40 RETURN CSB_CHEF BREAK
        CASE 41 RETURN CSB_CHIN_GOON BREAK
        CASE 42 RETURN CSB_CLETUS BREAK
        CASE 43 RETURN CSB_COP BREAK
        CASE 44 RETURN CSB_CUSTOMER BREAK
        CASE 45 RETURN CSB_DENISE_FRIEND BREAK
        CASE 46 RETURN CSB_FOS_REP BREAK
        CASE 47 RETURN CSB_G BREAK
        CASE 48 RETURN CSB_GROOM BREAK
        CASE 49 RETURN CSB_GROVE_STR_DLR BREAK
        CASE 50 RETURN CSB_HAO BREAK
        CASE 51 RETURN CSB_HUGH BREAK
        CASE 52 RETURN CSB_IMRAN BREAK
        CASE 53 RETURN CSB_JACKHOWITZER BREAK
        CASE 54 RETURN CSB_JANITOR BREAK
        CASE 55 RETURN CSB_MAUDE BREAK
        CASE 56 RETURN CSB_MWEATHER BREAK
        CASE 57 RETURN CSB_ORTEGA BREAK
        CASE 58 RETURN CSB_OSCAR BREAK
        CASE 59 RETURN CSB_PORNDUDES BREAK
        CASE 60 RETURN CSB_PROLOGUEDRIVER BREAK
        CASE 61 RETURN CSB_PROLSEC BREAK
        CASE 62 RETURN CSB_RAMP_GANG BREAK
        CASE 63 RETURN CSB_RAMP_HIC BREAK
        CASE 64 RETURN CSB_RAMP_HIPSTER BREAK
        CASE 65 RETURN CSB_RAMP_MARINE BREAK
        CASE 66 RETURN CSB_RAMP_MEX BREAK
        CASE 67 RETURN CSB_REPORTER BREAK
        CASE 68 RETURN CSB_ROCCOPELOSI BREAK
        CASE 69 RETURN CSB_SCREEN_WRITER BREAK
        CASE 70 RETURN CSB_STRIPPER_01 BREAK
        CASE 71 RETURN CSB_STRIPPER_02 BREAK
        CASE 72 RETURN CSB_TONYA BREAK
        CASE 73 RETURN CSB_TRAFFICWARDEN BREAK
        CASE 74 RETURN CS_AMANDATOWNLEY BREAK
        CASE 75 RETURN CS_ANDREAS BREAK
        CASE 76 RETURN CS_ASHLEY BREAK
        CASE 77 RETURN CS_BANKMAN BREAK
        CASE 78 RETURN CS_BARRY BREAK
        CASE 79 RETURN CS_BEVERLY BREAK
        CASE 80 RETURN CS_BRAD BREAK
        CASE 81 RETURN CS_BRADCADAVER BREAK
        CASE 82 RETURN CS_CARBUYER BREAK
        CASE 83 RETURN CS_CASEY BREAK
        CASE 84 RETURN CS_CHENGSR BREAK
        CASE 85 RETURN CS_CHRISFORMAGE BREAK
        CASE 86 RETURN CS_CLAY BREAK
        CASE 87 RETURN CS_DALE BREAK
        CASE 88 RETURN CS_DAVENORTON BREAK
        CASE 89 RETURN CS_DEBRA BREAK
        CASE 90 RETURN CS_DENISE BREAK
        CASE 91 RETURN CS_DEVIN BREAK
        CASE 92 RETURN CS_DOM BREAK
        CASE 93 RETURN CS_DREYFUSS BREAK
        CASE 94 RETURN CS_DRFRIEDLANDER BREAK
        CASE 95 RETURN CS_FABIEN BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_2(INT choice)
    SWITCH choice
        CASE 0 RETURN "A_M_Y_KTOWN_02" BREAK
        CASE 1 RETURN "A_M_Y_LATINO_01" BREAK
        CASE 2 RETURN "A_M_Y_METHHEAD_01" BREAK
        CASE 3 RETURN "A_M_Y_MEXTHUG_01" BREAK
        CASE 4 RETURN "A_M_Y_MOTOX_01" BREAK
        CASE 5 RETURN "A_M_Y_MOTOX_02" BREAK
        CASE 6 RETURN "A_M_Y_MUSCLBEAC_01" BREAK
        CASE 7 RETURN "A_M_Y_MUSCLBEAC_02" BREAK
        CASE 8 RETURN "A_M_Y_POLYNESIAN_01" BREAK
        CASE 9 RETURN "A_M_Y_ROADCYC_01" BREAK
        CASE 10 RETURN "A_M_Y_RUNNER_01" BREAK
        CASE 11 RETURN "A_M_Y_RUNNER_02" BREAK
        CASE 12 RETURN "A_M_Y_SALTON_01" BREAK
        CASE 13 RETURN "A_M_Y_SKATER_01" BREAK
        CASE 14 RETURN "A_M_Y_SKATER_02" BREAK
        CASE 15 RETURN "A_M_Y_SOUCENT_01" BREAK
        CASE 16 RETURN "A_M_Y_SOUCENT_02" BREAK
        CASE 17 RETURN "A_M_Y_SOUCENT_03" BREAK
        CASE 18 RETURN "A_M_Y_SOUCENT_04" BREAK
        CASE 19 RETURN "A_M_Y_STBLA_01" BREAK
        CASE 20 RETURN "A_M_Y_STBLA_02" BREAK
        CASE 21 RETURN "A_M_Y_STLAT_01" BREAK
        CASE 22 RETURN "A_M_Y_STWHI_01" BREAK
        CASE 23 RETURN "A_M_Y_STWHI_02" BREAK
        CASE 24 RETURN "A_M_Y_SUNBATHE_01" BREAK
        CASE 25 RETURN "A_M_Y_SURFER_01" BREAK
        CASE 26 RETURN "A_M_Y_VINDOUCHE_01" BREAK
        CASE 27 RETURN "A_M_Y_VINEWOOD_01" BREAK
        CASE 28 RETURN "A_M_Y_VINEWOOD_02" BREAK
        CASE 29 RETURN "A_M_Y_VINEWOOD_03" BREAK
        CASE 30 RETURN "A_M_Y_VINEWOOD_04" BREAK
        CASE 31 RETURN "A_M_Y_YOGA_01" BREAK
        CASE 32 RETURN "CSB_ABIGAIL" BREAK
        CASE 33 RETURN "CSB_ANITA" BREAK
        CASE 34 RETURN "CSB_ANTON" BREAK
        CASE 35 RETURN "CSB_BALLASOG" BREAK
        CASE 36 RETURN "CSB_BRIDE" BREAK
        CASE 37 RETURN "CSB_BURGERDRUG" BREAK
        CASE 38 RETURN "CSB_CAR3GUY1" BREAK
        CASE 39 RETURN "CSB_CAR3GUY2" BREAK
        CASE 40 RETURN "CSB_CHEF" BREAK
        CASE 41 RETURN "CSB_CHIN_GOON" BREAK
        CASE 42 RETURN "CSB_CLETUS" BREAK
        CASE 43 RETURN "CSB_COP" BREAK
        CASE 44 RETURN "CSB_CUSTOMER" BREAK
        CASE 45 RETURN "CSB_DENISE_FRIEND" BREAK
        CASE 46 RETURN "CSB_FOS_REP" BREAK
        CASE 47 RETURN "CSB_G" BREAK
        CASE 48 RETURN "CSB_GROOM" BREAK
        CASE 49 RETURN "CSB_GROVE_STR_DLR" BREAK
        CASE 50 RETURN "CSB_HAO" BREAK
        CASE 51 RETURN "CSB_HUGH" BREAK
        CASE 52 RETURN "CSB_IMRAN" BREAK
        CASE 53 RETURN "CSB_JACKHOWITZER" BREAK
        CASE 54 RETURN "CSB_JANITOR" BREAK
        CASE 55 RETURN "CSB_MAUDE" BREAK
        CASE 56 RETURN "CSB_MWEATHER" BREAK
        CASE 57 RETURN "CSB_ORTEGA" BREAK
        CASE 58 RETURN "CSB_OSCAR" BREAK
        CASE 59 RETURN "CSB_PORNDUDES" BREAK
        CASE 60 RETURN "CSB_PROLOGUEDRIVER" BREAK
        CASE 61 RETURN "CSB_PROLSEC" BREAK
        CASE 62 RETURN "CSB_RAMP_GANG" BREAK
        CASE 63 RETURN "CSB_RAMP_HIC" BREAK
        CASE 64 RETURN "CSB_RAMP_HIPSTER" BREAK
        CASE 65 RETURN "CSB_RAMP_MARINE" BREAK
        CASE 66 RETURN "CSB_RAMP_MEX" BREAK
        CASE 67 RETURN "CSB_REPORTER" BREAK
        CASE 68 RETURN "CSB_ROCCOPELOSI" BREAK
        CASE 69 RETURN "CSB_SCREEN_WRITER" BREAK
        CASE 70 RETURN "CSB_STRIPPER_01" BREAK
        CASE 71 RETURN "CSB_STRIPPER_02" BREAK
        CASE 72 RETURN "CSB_TONYA" BREAK
        CASE 73 RETURN "CSB_TRAFFICWARDEN" BREAK
        CASE 74 RETURN "CS_AMANDATOWNLEY" BREAK
        CASE 75 RETURN "CS_ANDREAS" BREAK
        CASE 76 RETURN "CS_ASHLEY" BREAK
        CASE 77 RETURN "CS_BANKMAN" BREAK
        CASE 78 RETURN "CS_BARRY" BREAK
        CASE 79 RETURN "CS_BEVERLY" BREAK
        CASE 80 RETURN "CS_BRAD" BREAK
        CASE 81 RETURN "CS_BRADCADAVER" BREAK
        CASE 82 RETURN "CS_CARBUYER" BREAK
        CASE 83 RETURN "CS_CASEY" BREAK
        CASE 84 RETURN "CS_CHENGSR" BREAK
        CASE 85 RETURN "CS_CHRISFORMAGE" BREAK
        CASE 86 RETURN "CS_CLAY" BREAK
        CASE 87 RETURN "CS_DALE" BREAK
        CASE 88 RETURN "CS_DAVENORTON" BREAK
        CASE 89 RETURN "CS_DEBRA" BREAK
        CASE 90 RETURN "CS_DENISE" BREAK
        CASE 91 RETURN "CS_DEVIN" BREAK
        CASE 92 RETURN "CS_DOM" BREAK
        CASE 93 RETURN "CS_DREYFUSS" BREAK
        CASE 94 RETURN "CS_DRFRIEDLANDER" BREAK
        CASE 95 RETURN "CS_FABIEN" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_3(INT choice)
    SWITCH choice
        CASE 0 RETURN CS_FBISUIT_01 BREAK
        CASE 1 RETURN CS_FLOYD BREAK
        CASE 2 RETURN CS_GUADALOPE BREAK
        CASE 3 RETURN CS_GURK BREAK
        CASE 4 RETURN CS_HUNTER BREAK
        CASE 5 RETURN CS_JANET BREAK
        CASE 6 RETURN CS_JEWELASS BREAK
        CASE 7 RETURN CS_JIMMYBOSTON BREAK
        CASE 8 RETURN CS_JIMMYDISANTO BREAK
        CASE 9 RETURN CS_JOEMINUTEMAN BREAK
        CASE 10 RETURN CS_JOHNNYKLEBITZ BREAK
        CASE 11 RETURN CS_JOSEF BREAK
        CASE 12 RETURN CS_JOSH BREAK
        CASE 13 RETURN CS_LAMARDAVIS BREAK
        CASE 14 RETURN CS_LAZLOW BREAK
        CASE 15 RETURN CS_LESTERCREST BREAK
        CASE 16 RETURN CS_LIFEINVAD_01 BREAK
        CASE 17 RETURN CS_MAGENTA BREAK
        CASE 18 RETURN CS_MANUEL BREAK
        CASE 19 RETURN CS_MARNIE BREAK
        CASE 20 RETURN CS_MARTINMADRAZO BREAK
        CASE 21 RETURN CS_MARYANN BREAK
        CASE 22 RETURN CS_MICHELLE BREAK
        CASE 23 RETURN CS_MILTON BREAK
        CASE 24 RETURN CS_MOLLY BREAK
        CASE 25 RETURN CS_MOVPREMF_01 BREAK
        CASE 26 RETURN CS_MOVPREMMALE BREAK
        CASE 27 RETURN CS_MRK BREAK
        CASE 28 RETURN CS_MRSPHILLIPS BREAK
        CASE 29 RETURN CS_MRS_THORNHILL BREAK
        CASE 30 RETURN CS_NATALIA BREAK
        CASE 31 RETURN CS_NERVOUSRON BREAK
        CASE 32 RETURN CS_NIGEL BREAK
        CASE 33 RETURN CS_OLD_MAN1A BREAK
        CASE 34 RETURN CS_OLD_MAN2 BREAK
        CASE 35 RETURN CS_OMEGA BREAK
        CASE 36 RETURN CS_ORLEANS BREAK
        CASE 37 RETURN CS_PAPER BREAK
        CASE 38 RETURN CS_PATRICIA BREAK
        CASE 39 RETURN CS_PRIEST BREAK
        CASE 40 RETURN CS_PROLSEC_02 BREAK
        CASE 41 RETURN CS_RUSSIANDRUNK BREAK
        CASE 42 RETURN CS_SIEMONYETARIAN BREAK
        CASE 43 RETURN CS_SOLOMON BREAK
        CASE 44 RETURN CS_STEVEHAINS BREAK
        CASE 45 RETURN CS_STRETCH BREAK
        CASE 46 RETURN CS_TANISHA BREAK
        CASE 47 RETURN CS_TAOCHENG BREAK
        CASE 48 RETURN CS_TAOSTRANSLATOR BREAK
        CASE 49 RETURN CS_TENNISCOACH BREAK
        CASE 50 RETURN CS_TERRY BREAK
        CASE 51 RETURN CS_TOM BREAK
        CASE 52 RETURN CS_TOMEPSILON BREAK
        CASE 53 RETURN CS_TRACYDISANTO BREAK
        CASE 54 RETURN CS_WADE BREAK
        CASE 55 RETURN CS_ZIMBOR BREAK
        CASE 56 RETURN G_F_Y_BALLAS_01 BREAK
        CASE 57 RETURN G_F_Y_FAMILIES_01 BREAK
        CASE 58 RETURN G_F_Y_LOST_01 BREAK
        CASE 59 RETURN G_F_Y_VAGOS_01 BREAK
        CASE 60 RETURN G_M_M_ARMBOSS_01 BREAK
        CASE 61 RETURN G_M_M_ARMGOON_01 BREAK
        CASE 62 RETURN G_M_M_ARMLIEUT_01 BREAK
        CASE 63 RETURN G_M_M_CHEMWORK_01 BREAK
        CASE 64 RETURN G_M_M_CHIBOSS_01 BREAK
        CASE 65 RETURN G_M_M_CHICOLD_01 BREAK
        CASE 66 RETURN G_M_M_CHIGOON_01 BREAK
        CASE 67 RETURN G_M_M_CHIGOON_02 BREAK
        CASE 68 RETURN G_M_M_KORBOSS_01 BREAK
        CASE 69 RETURN G_M_M_MEXBOSS_01 BREAK
        CASE 70 RETURN G_M_M_MEXBOSS_02 BREAK
        CASE 71 RETURN G_M_Y_ARMGOON_02 BREAK
        CASE 72 RETURN G_M_Y_AZTECA_01 BREAK
        CASE 73 RETURN G_M_Y_BALLAEAST_01 BREAK
        CASE 74 RETURN G_M_Y_BALLAORIG_01 BREAK
        CASE 75 RETURN G_M_Y_BALLASOUT_01 BREAK
        CASE 76 RETURN G_M_Y_FAMCA_01 BREAK
        CASE 77 RETURN G_M_Y_FAMDNF_01 BREAK
        CASE 78 RETURN G_M_Y_FAMFOR_01 BREAK
        CASE 79 RETURN G_M_Y_KOREAN_01 BREAK
        CASE 80 RETURN G_M_Y_KOREAN_02 BREAK
        CASE 81 RETURN G_M_Y_KORLIEUT_01 BREAK
        CASE 82 RETURN G_M_Y_LOST_01 BREAK
        CASE 83 RETURN G_M_Y_LOST_02 BREAK
        CASE 84 RETURN G_M_Y_LOST_03 BREAK
        CASE 85 RETURN G_M_Y_MEXGANG_01 BREAK
        CASE 86 RETURN G_M_Y_MEXGOON_01 BREAK
        CASE 87 RETURN G_M_Y_MEXGOON_02 BREAK
        CASE 88 RETURN G_M_Y_MEXGOON_03 BREAK
        CASE 89 RETURN G_M_Y_POLOGOON_01 BREAK
        CASE 90 RETURN G_M_Y_POLOGOON_02 BREAK
        CASE 91 RETURN G_M_Y_SALVABOSS_01 BREAK
        CASE 92 RETURN G_M_Y_SALVAGOON_01 BREAK
        CASE 93 RETURN G_M_Y_SALVAGOON_02 BREAK
        CASE 94 RETURN G_M_Y_SALVAGOON_03 BREAK
        CASE 95 RETURN G_M_Y_STRPUNK_01 BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_3(INT choice)
    SWITCH choice
        CASE 0 RETURN "CS_FBISUIT_01" BREAK
        CASE 1 RETURN "CS_FLOYD" BREAK
        CASE 2 RETURN "CS_GUADALOPE" BREAK
        CASE 3 RETURN "CS_GURK" BREAK
        CASE 4 RETURN "CS_HUNTER" BREAK
        CASE 5 RETURN "CS_JANET" BREAK
        CASE 6 RETURN "CS_JEWELASS" BREAK
        CASE 7 RETURN "CS_JIMMYBOSTON" BREAK
        CASE 8 RETURN "CS_JIMMYDISANTO" BREAK
        CASE 9 RETURN "CS_JOEMINUTEMAN" BREAK
        CASE 10 RETURN "CS_JOHNNYKLEBITZ" BREAK
        CASE 11 RETURN "CS_JOSEF" BREAK
        CASE 12 RETURN "CS_JOSH" BREAK
        CASE 13 RETURN "CS_LAMARDAVIS" BREAK
        CASE 14 RETURN "CS_LAZLOW" BREAK
        CASE 15 RETURN "CS_LESTERCREST" BREAK
        CASE 16 RETURN "CS_LIFEINVAD_01" BREAK
        CASE 17 RETURN "CS_MAGENTA" BREAK
        CASE 18 RETURN "CS_MANUEL" BREAK
        CASE 19 RETURN "CS_MARNIE" BREAK
        CASE 20 RETURN "CS_MARTINMADRAZO" BREAK
        CASE 21 RETURN "CS_MARYANN" BREAK
        CASE 22 RETURN "CS_MICHELLE" BREAK
        CASE 23 RETURN "CS_MILTON" BREAK
        CASE 24 RETURN "CS_MOLLY" BREAK
        CASE 25 RETURN "CS_MOVPREMF_01" BREAK
        CASE 26 RETURN "CS_MOVPREMMALE" BREAK
        CASE 27 RETURN "CS_MRK" BREAK
        CASE 28 RETURN "CS_MRSPHILLIPS" BREAK
        CASE 29 RETURN "CS_MRS_THORNHILL" BREAK
        CASE 30 RETURN "CS_NATALIA" BREAK
        CASE 31 RETURN "CS_NERVOUSRON" BREAK
        CASE 32 RETURN "CS_NIGEL" BREAK
        CASE 33 RETURN "CS_OLD_MAN1A" BREAK
        CASE 34 RETURN "CS_OLD_MAN2" BREAK
        CASE 35 RETURN "CS_OMEGA" BREAK
        CASE 36 RETURN "CS_ORLEANS" BREAK
        CASE 37 RETURN "CS_PAPER" BREAK
        CASE 38 RETURN "CS_PATRICIA" BREAK
        CASE 39 RETURN "CS_PRIEST" BREAK
        CASE 40 RETURN "CS_PROLSEC_02" BREAK
        CASE 41 RETURN "CS_RUSSIANDRUNK" BREAK
        CASE 42 RETURN "CS_SIEMONYETARIAN" BREAK
        CASE 43 RETURN "CS_SOLOMON" BREAK
        CASE 44 RETURN "CS_STEVEHAINS" BREAK
        CASE 45 RETURN "CS_STRETCH" BREAK
        CASE 46 RETURN "CS_TANISHA" BREAK
        CASE 47 RETURN "CS_TAOCHENG" BREAK
        CASE 48 RETURN "CS_TAOSTRANSLATOR" BREAK
        CASE 49 RETURN "CS_TENNISCOACH" BREAK
        CASE 50 RETURN "CS_TERRY" BREAK
        CASE 51 RETURN "CS_TOM" BREAK
        CASE 52 RETURN "CS_TOMEPSILON" BREAK
        CASE 53 RETURN "CS_TRACYDISANTO" BREAK
        CASE 54 RETURN "CS_WADE" BREAK
        CASE 55 RETURN "CS_ZIMBOR" BREAK
        CASE 56 RETURN "G_F_Y_BALLAS_01" BREAK
        CASE 57 RETURN "G_F_Y_FAMILIES_01" BREAK
        CASE 58 RETURN "G_F_Y_LOST_01" BREAK
        CASE 59 RETURN "G_F_Y_VAGOS_01" BREAK
        CASE 60 RETURN "G_M_M_ARMBOSS_01" BREAK
        CASE 61 RETURN "G_M_M_ARMGOON_01" BREAK
        CASE 62 RETURN "G_M_M_ARMLIEUT_01" BREAK
        CASE 63 RETURN "G_M_M_CHEMWORK_01" BREAK
        CASE 64 RETURN "G_M_M_CHIBOSS_01" BREAK
        CASE 65 RETURN "G_M_M_CHICOLD_01" BREAK
        CASE 66 RETURN "G_M_M_CHIGOON_01" BREAK
        CASE 67 RETURN "G_M_M_CHIGOON_02" BREAK
        CASE 68 RETURN "G_M_M_KORBOSS_01" BREAK
        CASE 69 RETURN "G_M_M_MEXBOSS_01" BREAK
        CASE 70 RETURN "G_M_M_MEXBOSS_02" BREAK
        CASE 71 RETURN "G_M_Y_ARMGOON_02" BREAK
        CASE 72 RETURN "G_M_Y_AZTECA_01" BREAK
        CASE 73 RETURN "G_M_Y_BALLAEAST_01" BREAK
        CASE 74 RETURN "G_M_Y_BALLAORIG_01" BREAK
        CASE 75 RETURN "G_M_Y_BALLASOUT_01" BREAK
        CASE 76 RETURN "G_M_Y_FAMCA_01" BREAK
        CASE 77 RETURN "G_M_Y_FAMDNF_01" BREAK
        CASE 78 RETURN "G_M_Y_FAMFOR_01" BREAK
        CASE 79 RETURN "G_M_Y_KOREAN_01" BREAK
        CASE 80 RETURN "G_M_Y_KOREAN_02" BREAK
        CASE 81 RETURN "G_M_Y_KORLIEUT_01" BREAK
        CASE 82 RETURN "G_M_Y_LOST_01" BREAK
        CASE 83 RETURN "G_M_Y_LOST_02" BREAK
        CASE 84 RETURN "G_M_Y_LOST_03" BREAK
        CASE 85 RETURN "G_M_Y_MEXGANG_01" BREAK
        CASE 86 RETURN "G_M_Y_MEXGOON_01" BREAK
        CASE 87 RETURN "G_M_Y_MEXGOON_02" BREAK
        CASE 88 RETURN "G_M_Y_MEXGOON_03" BREAK
        CASE 89 RETURN "G_M_Y_POLOGOON_01" BREAK
        CASE 90 RETURN "G_M_Y_POLOGOON_02" BREAK
        CASE 91 RETURN "G_M_Y_SALVABOSS_01" BREAK
        CASE 92 RETURN "G_M_Y_SALVAGOON_01" BREAK
        CASE 93 RETURN "G_M_Y_SALVAGOON_02" BREAK
        CASE 94 RETURN "G_M_Y_SALVAGOON_03" BREAK
        CASE 95 RETURN "G_M_Y_STRPUNK_01" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_4(INT choice)
    SWITCH choice
        CASE 0 RETURN G_M_Y_STRPUNK_02 BREAK
        CASE 1 RETURN HC_DRIVER BREAK
        CASE 2 RETURN HC_GUNMAN BREAK
        CASE 3 RETURN HC_HACKER BREAK
        CASE 4 RETURN IG_ABIGAIL BREAK
        CASE 5 RETURN IG_AMANDATOWNLEY BREAK
        CASE 6 RETURN IG_ANDREAS BREAK
        CASE 7 RETURN IG_ASHLEY BREAK
        CASE 8 RETURN IG_BALLASOG BREAK
        CASE 9 RETURN IG_BANKMAN BREAK
        CASE 10 RETURN IG_BARRY BREAK
        CASE 11 RETURN IG_BESTMEN BREAK
        CASE 12 RETURN IG_BEVERLY BREAK
        CASE 13 RETURN IG_BRAD BREAK
        CASE 14 RETURN IG_BRIDE BREAK
        CASE 15 RETURN IG_CAR3GUY1 BREAK
        CASE 16 RETURN IG_CAR3GUY2 BREAK
        CASE 17 RETURN IG_CASEY BREAK
        CASE 18 RETURN IG_CHEF BREAK
        CASE 19 RETURN IG_CHENGSR BREAK
        CASE 20 RETURN IG_CHRISFORMAGE BREAK
        CASE 21 RETURN IG_CLAY BREAK
        CASE 22 RETURN IG_CLAYPAIN BREAK
        CASE 23 RETURN IG_CLETUS BREAK
        CASE 24 RETURN IG_DALE BREAK
        CASE 25 RETURN IG_DAVENORTON BREAK
        CASE 26 RETURN IG_DENISE BREAK
        CASE 27 RETURN IG_DEVIN BREAK
        CASE 28 RETURN IG_DOM BREAK
        CASE 29 RETURN IG_DREYFUSS BREAK
        CASE 30 RETURN IG_DRFRIEDLANDER BREAK
        CASE 31 RETURN IG_FABIEN BREAK
        CASE 32 RETURN IG_FBISUIT_01 BREAK
        CASE 33 RETURN IG_FLOYD BREAK
        CASE 34 RETURN IG_GROOM BREAK
        CASE 35 RETURN IG_HAO BREAK
        CASE 36 RETURN IG_HUNTER BREAK
        CASE 37 RETURN IG_JANET BREAK
        CASE 38 RETURN IG_JAY_NORRIS BREAK
        CASE 39 RETURN IG_JEWELASS BREAK
        CASE 40 RETURN IG_JIMMYBOSTON BREAK
        CASE 41 RETURN IG_JIMMYDISANTO BREAK
        CASE 42 RETURN IG_JOEMINUTEMAN BREAK
        CASE 43 RETURN IG_JOHNNYKLEBITZ BREAK
        CASE 44 RETURN IG_JOSEF BREAK
        CASE 45 RETURN IG_JOSH BREAK
        CASE 46 RETURN IG_KERRYMCINTOSH BREAK
        CASE 47 RETURN IG_LAMARDAVIS BREAK
        CASE 48 RETURN IG_LAZLOW BREAK
        CASE 49 RETURN IG_LESTERCREST BREAK
        CASE 50 RETURN IG_LIFEINVAD_01 BREAK
        CASE 51 RETURN IG_LIFEINVAD_02 BREAK
        CASE 52 RETURN IG_MAGENTA BREAK
        CASE 53 RETURN IG_MANUEL BREAK
        CASE 54 RETURN IG_MARNIE BREAK
        CASE 55 RETURN IG_MARYANN BREAK
        CASE 56 RETURN IG_MAUDE BREAK
        CASE 57 RETURN IG_MICHELLE BREAK
        CASE 58 RETURN IG_MILTON BREAK
        CASE 59 RETURN IG_MOLLY BREAK
        CASE 60 RETURN IG_MRK BREAK
        CASE 61 RETURN IG_MRSPHILLIPS BREAK
        CASE 62 RETURN IG_MRS_THORNHILL BREAK
        CASE 63 RETURN IG_NATALIA BREAK
        CASE 64 RETURN IG_NERVOUSRON BREAK
        CASE 65 RETURN IG_NIGEL BREAK
        CASE 66 RETURN IG_OLD_MAN1A BREAK
        CASE 67 RETURN IG_OLD_MAN2 BREAK
        CASE 68 RETURN IG_OMEGA BREAK
        CASE 69 RETURN IG_ONEIL BREAK
        CASE 70 RETURN IG_ORLEANS BREAK
        CASE 71 RETURN IG_ORTEGA BREAK
        CASE 72 RETURN IG_PAPER BREAK
        CASE 73 RETURN IG_PATRICIA BREAK
        CASE 74 RETURN IG_PRIEST BREAK
        CASE 75 RETURN IG_PROLSEC_02 BREAK
        CASE 76 RETURN IG_RAMP_GANG BREAK
        CASE 77 RETURN IG_RAMP_HIC BREAK
        CASE 78 RETURN IG_RAMP_HIPSTER BREAK
        CASE 79 RETURN IG_RAMP_MEX BREAK
        CASE 80 RETURN IG_ROCCOPELOSI BREAK
        CASE 81 RETURN IG_RUSSIANDRUNK BREAK
        CASE 82 RETURN IG_SCREEN_WRITER BREAK
        CASE 83 RETURN IG_SIEMONYETARIAN BREAK
        CASE 84 RETURN IG_SOLOMON BREAK
        CASE 85 RETURN IG_STEVEHAINS BREAK
        CASE 86 RETURN IG_STRETCH BREAK
        CASE 87 RETURN IG_TALINA BREAK
        CASE 88 RETURN IG_TANISHA BREAK
        CASE 89 RETURN IG_TAOCHENG BREAK
        CASE 90 RETURN IG_TAOSTRANSLATOR BREAK
        CASE 91 RETURN IG_TENNISCOACH BREAK
        CASE 92 RETURN IG_TERRY BREAK
        CASE 93 RETURN IG_TOMEPSILON BREAK
        CASE 94 RETURN IG_TONYA BREAK
        CASE 95 RETURN IG_TRACYDISANTO BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_4(INT choice)
    SWITCH choice
        CASE 0 RETURN "G_M_Y_STRPUNK_02" BREAK
        CASE 1 RETURN "HC_DRIVER" BREAK
        CASE 2 RETURN "HC_GUNMAN" BREAK
        CASE 3 RETURN "HC_HACKER" BREAK
        CASE 4 RETURN "IG_ABIGAIL" BREAK
        CASE 5 RETURN "IG_AMANDATOWNLEY" BREAK
        CASE 6 RETURN "IG_ANDREAS" BREAK
        CASE 7 RETURN "IG_ASHLEY" BREAK
        CASE 8 RETURN "IG_BALLASOG" BREAK
        CASE 9 RETURN "IG_BANKMAN" BREAK
        CASE 10 RETURN "IG_BARRY" BREAK
        CASE 11 RETURN "IG_BESTMEN" BREAK
        CASE 12 RETURN "IG_BEVERLY" BREAK
        CASE 13 RETURN "IG_BRAD" BREAK
        CASE 14 RETURN "IG_BRIDE" BREAK
        CASE 15 RETURN "IG_CAR3GUY1" BREAK
        CASE 16 RETURN "IG_CAR3GUY2" BREAK
        CASE 17 RETURN "IG_CASEY" BREAK
        CASE 18 RETURN "IG_CHEF" BREAK
        CASE 19 RETURN "IG_CHENGSR" BREAK
        CASE 20 RETURN "IG_CHRISFORMAGE" BREAK
        CASE 21 RETURN "IG_CLAY" BREAK
        CASE 22 RETURN "IG_CLAYPAIN" BREAK
        CASE 23 RETURN "IG_CLETUS" BREAK
        CASE 24 RETURN "IG_DALE" BREAK
        CASE 25 RETURN "IG_DAVENORTON" BREAK
        CASE 26 RETURN "IG_DENISE" BREAK
        CASE 27 RETURN "IG_DEVIN" BREAK
        CASE 28 RETURN "IG_DOM" BREAK
        CASE 29 RETURN "IG_DREYFUSS" BREAK
        CASE 30 RETURN "IG_DRFRIEDLANDER" BREAK
        CASE 31 RETURN "IG_FABIEN" BREAK
        CASE 32 RETURN "IG_FBISUIT_01" BREAK
        CASE 33 RETURN "IG_FLOYD" BREAK
        CASE 34 RETURN "IG_GROOM" BREAK
        CASE 35 RETURN "IG_HAO" BREAK
        CASE 36 RETURN "IG_HUNTER" BREAK
        CASE 37 RETURN "IG_JANET" BREAK
        CASE 38 RETURN "IG_JAY_NORRIS" BREAK
        CASE 39 RETURN "IG_JEWELASS" BREAK
        CASE 40 RETURN "IG_JIMMYBOSTON" BREAK
        CASE 41 RETURN "IG_JIMMYDISANTO" BREAK
        CASE 42 RETURN "IG_JOEMINUTEMAN" BREAK
        CASE 43 RETURN "IG_JOHNNYKLEBITZ" BREAK
        CASE 44 RETURN "IG_JOSEF" BREAK
        CASE 45 RETURN "IG_JOSH" BREAK
        CASE 46 RETURN "IG_KERRYMCINTOSH" BREAK
        CASE 47 RETURN "IG_LAMARDAVIS" BREAK
        CASE 48 RETURN "IG_LAZLOW" BREAK
        CASE 49 RETURN "IG_LESTERCREST" BREAK
        CASE 50 RETURN "IG_LIFEINVAD_01" BREAK
        CASE 51 RETURN "IG_LIFEINVAD_02" BREAK
        CASE 52 RETURN "IG_MAGENTA" BREAK
        CASE 53 RETURN "IG_MANUEL" BREAK
        CASE 54 RETURN "IG_MARNIE" BREAK
        CASE 55 RETURN "IG_MARYANN" BREAK
        CASE 56 RETURN "IG_MAUDE" BREAK
        CASE 57 RETURN "IG_MICHELLE" BREAK
        CASE 58 RETURN "IG_MILTON" BREAK
        CASE 59 RETURN "IG_MOLLY" BREAK
        CASE 60 RETURN "IG_MRK" BREAK
        CASE 61 RETURN "IG_MRSPHILLIPS" BREAK
        CASE 62 RETURN "IG_MRS_THORNHILL" BREAK
        CASE 63 RETURN "IG_NATALIA" BREAK
        CASE 64 RETURN "IG_NERVOUSRON" BREAK
        CASE 65 RETURN "IG_NIGEL" BREAK
        CASE 66 RETURN "IG_OLD_MAN1A" BREAK
        CASE 67 RETURN "IG_OLD_MAN2" BREAK
        CASE 68 RETURN "IG_OMEGA" BREAK
        CASE 69 RETURN "IG_ONEIL" BREAK
        CASE 70 RETURN "IG_ORLEANS" BREAK
        CASE 71 RETURN "IG_ORTEGA" BREAK
        CASE 72 RETURN "IG_PAPER" BREAK
        CASE 73 RETURN "IG_PATRICIA" BREAK
        CASE 74 RETURN "IG_PRIEST" BREAK
        CASE 75 RETURN "IG_PROLSEC_02" BREAK
        CASE 76 RETURN "IG_RAMP_GANG" BREAK
        CASE 77 RETURN "IG_RAMP_HIC" BREAK
        CASE 78 RETURN "IG_RAMP_HIPSTER" BREAK
        CASE 79 RETURN "IG_RAMP_MEX" BREAK
        CASE 80 RETURN "IG_ROCCOPELOSI" BREAK
        CASE 81 RETURN "IG_RUSSIANDRUNK" BREAK
        CASE 82 RETURN "IG_SCREEN_WRITER" BREAK
        CASE 83 RETURN "IG_SIEMONYETARIAN" BREAK
        CASE 84 RETURN "IG_SOLOMON" BREAK
        CASE 85 RETURN "IG_STEVEHAINS" BREAK
        CASE 86 RETURN "IG_STRETCH" BREAK
        CASE 87 RETURN "IG_TALINA" BREAK
        CASE 88 RETURN "IG_TANISHA" BREAK
        CASE 89 RETURN "IG_TAOCHENG" BREAK
        CASE 90 RETURN "IG_TAOSTRANSLATOR" BREAK
        CASE 91 RETURN "IG_TENNISCOACH" BREAK
        CASE 92 RETURN "IG_TERRY" BREAK
        CASE 93 RETURN "IG_TOMEPSILON" BREAK
        CASE 94 RETURN "IG_TONYA" BREAK
        CASE 95 RETURN "IG_TRACYDISANTO" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_5(INT choice)
    SWITCH choice
        CASE 0 RETURN IG_TRAFFICWARDEN BREAK
        CASE 1 RETURN IG_TYLERDIX BREAK
        CASE 2 RETURN IG_WADE BREAK
        CASE 3 RETURN IG_ZIMBOR BREAK
        CASE 4 RETURN MP_F_DEADHOOKER BREAK
        CASE 5 RETURN MP_F_FREEMODE_01 BREAK
        CASE 6 RETURN MP_F_MISTY_01 BREAK
        CASE 7 RETURN MP_F_STRIPPERLITE BREAK
        CASE 8 RETURN MP_G_M_PROS_01 BREAK
        CASE 9 RETURN MP_HEADTARGETS BREAK
        CASE 10 RETURN MP_M_CLAUDE_01 BREAK
        CASE 11 RETURN MP_M_EXARMY_01 BREAK
        CASE 12 RETURN MP_M_FAMDD_01 BREAK
        CASE 13 RETURN MP_M_FIBSEC_01 BREAK
        CASE 14 RETURN MP_M_FREEMODE_01 BREAK
        CASE 15 RETURN MP_M_MARSTON_01 BREAK
        CASE 16 RETURN MP_M_NIKO_01 BREAK
        CASE 17 RETURN MP_M_SHOPKEEP_01 BREAK
        CASE 18 RETURN MP_S_M_ARMOURED_01 BREAK
        CASE 19 RETURN PLAYER_ONE BREAK
        CASE 20 RETURN PLAYER_TWO BREAK
        CASE 21 RETURN PLAYER_ZERO BREAK
        CASE 22 RETURN SLOD_HUMAN BREAK
        CASE 23 RETURN SLOD_LARGE_QUADPED BREAK
        CASE 24 RETURN SLOD_SMALL_QUADPED BREAK
        CASE 25 RETURN S_F_M_FEMBARBER BREAK
        CASE 26 RETURN S_F_M_MAID_01 BREAK
        CASE 27 RETURN S_F_M_SHOP_HIGH BREAK
        CASE 28 RETURN S_F_M_SWEATSHOP_01 BREAK
        CASE 29 RETURN S_F_Y_AIRHOSTESS_01 BREAK
        CASE 30 RETURN S_F_Y_BARTENDER_01 BREAK
        CASE 31 RETURN S_F_Y_BAYWATCH_01 BREAK
        CASE 32 RETURN S_F_Y_COP_01 BREAK
        CASE 33 RETURN S_F_Y_FACTORY_01 BREAK
        CASE 34 RETURN S_F_Y_HOOKER_01 BREAK
        CASE 35 RETURN S_F_Y_HOOKER_02 BREAK
        CASE 36 RETURN S_F_Y_HOOKER_03 BREAK
        CASE 37 RETURN S_F_Y_MIGRANT_01 BREAK
        CASE 38 RETURN S_F_Y_MOVPREM_01 BREAK
        CASE 39 RETURN S_F_Y_RANGER_01 BREAK
        CASE 40 RETURN S_F_Y_SCRUBS_01 BREAK
        CASE 41 RETURN S_F_Y_SHERIFF_01 BREAK
        CASE 42 RETURN S_F_Y_SHOP_LOW BREAK
        CASE 43 RETURN S_F_Y_SHOP_MID BREAK
        CASE 44 RETURN S_F_Y_STRIPPERLITE BREAK
        CASE 45 RETURN S_F_Y_STRIPPER_01 BREAK
        CASE 46 RETURN S_F_Y_STRIPPER_02 BREAK
        CASE 47 RETURN S_F_Y_SWEATSHOP_01 BREAK
        CASE 48 RETURN S_M_M_AMMUCOUNTRY BREAK
        CASE 49 RETURN S_M_M_ARMOURED_01 BREAK
        CASE 50 RETURN S_M_M_ARMOURED_02 BREAK
        CASE 51 RETURN S_M_M_AUTOSHOP_01 BREAK
        CASE 52 RETURN S_M_M_AUTOSHOP_02 BREAK
        CASE 53 RETURN S_M_M_BOUNCER_01 BREAK
        CASE 54 RETURN S_M_M_CHEMSEC_01 BREAK
        CASE 55 RETURN S_M_M_CIASEC_01 BREAK
        CASE 56 RETURN S_M_M_CNTRYBAR_01 BREAK
        CASE 57 RETURN S_M_M_DOCKWORK_01 BREAK
        CASE 58 RETURN S_M_M_DOCTOR_01 BREAK
        CASE 59 RETURN S_M_M_FIBOFFICE_01 BREAK
        CASE 60 RETURN S_M_M_FIBOFFICE_02 BREAK
        CASE 61 RETURN S_M_M_GAFFER_01 BREAK
        CASE 62 RETURN S_M_M_GARDENER_01 BREAK
        CASE 63 RETURN S_M_M_GENTRANSPORT BREAK
        CASE 64 RETURN S_M_M_HAIRDRESS_01 BREAK
        CASE 65 RETURN S_M_M_HIGHSEC_01 BREAK
        CASE 66 RETURN S_M_M_HIGHSEC_02 BREAK
        CASE 67 RETURN S_M_M_JANITOR BREAK
        CASE 68 RETURN S_M_M_LATHANDY_01 BREAK
        CASE 69 RETURN S_M_M_LIFEINVAD_01 BREAK
        CASE 70 RETURN S_M_M_LINECOOK BREAK
        CASE 71 RETURN S_M_M_LSMETRO_01 BREAK
        CASE 72 RETURN S_M_M_MARIACHI_01 BREAK
        CASE 73 RETURN S_M_M_MARINE_01 BREAK
        CASE 74 RETURN S_M_M_MARINE_02 BREAK
        CASE 75 RETURN S_M_M_MIGRANT_01 BREAK
        CASE 76 RETURN S_M_M_MOVALIEN_01 BREAK
        CASE 77 RETURN S_M_M_MOVPREM_01 BREAK
        CASE 78 RETURN S_M_M_MOVSPACE_01 BREAK
        CASE 79 RETURN S_M_M_PARAMEDIC_01 BREAK
        CASE 80 RETURN S_M_M_PILOT_01 BREAK
        CASE 81 RETURN S_M_M_PILOT_02 BREAK
        CASE 82 RETURN S_M_M_POSTAL_01 BREAK
        CASE 83 RETURN S_M_M_POSTAL_02 BREAK
        CASE 84 RETURN S_M_M_PRISGUARD_01 BREAK
        CASE 85 RETURN S_M_M_SCIENTIST_01 BREAK
        CASE 86 RETURN S_M_M_SECURITY_01 BREAK
        CASE 87 RETURN S_M_M_SNOWCOP_01 BREAK
        CASE 88 RETURN S_M_M_STRPERF_01 BREAK
        CASE 89 RETURN S_M_M_STRPREACH_01 BREAK
        CASE 90 RETURN S_M_M_STRVEND_01 BREAK
        CASE 91 RETURN S_M_M_TRUCKER_01 BREAK
        CASE 92 RETURN S_M_M_UPS_01 BREAK
        CASE 93 RETURN S_M_M_UPS_02 BREAK
        CASE 94 RETURN S_M_O_BUSKER_01 BREAK
        CASE 95 RETURN S_M_Y_AIRWORKER BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_5(INT choice)
    SWITCH choice
        CASE 0 RETURN "IG_TRAFFICWARDEN" BREAK
        CASE 1 RETURN "IG_TYLERDIX" BREAK
        CASE 2 RETURN "IG_WADE" BREAK
        CASE 3 RETURN "IG_ZIMBOR" BREAK
        CASE 4 RETURN "MP_F_DEADHOOKER" BREAK
        CASE 5 RETURN "MP_F_FREEMODE_01" BREAK
        CASE 6 RETURN "MP_F_MISTY_01" BREAK
        CASE 7 RETURN "MP_F_STRIPPERLITE" BREAK
        CASE 8 RETURN "MP_G_M_PROS_01" BREAK
        CASE 9 RETURN "MP_HEADTARGETS" BREAK
        CASE 10 RETURN "MP_M_CLAUDE_01" BREAK
        CASE 11 RETURN "MP_M_EXARMY_01" BREAK
        CASE 12 RETURN "MP_M_FAMDD_01" BREAK
        CASE 13 RETURN "MP_M_FIBSEC_01" BREAK
        CASE 14 RETURN "MP_M_FREEMODE_01" BREAK
        CASE 15 RETURN "MP_M_MARSTON_01" BREAK
        CASE 16 RETURN "MP_M_NIKO_01" BREAK
        CASE 17 RETURN "MP_M_SHOPKEEP_01" BREAK
        CASE 18 RETURN "MP_S_M_ARMOURED_01" BREAK
        CASE 19 RETURN "PLAYER_ONE" BREAK
        CASE 20 RETURN "PLAYER_TWO" BREAK
        CASE 21 RETURN "PLAYER_ZERO" BREAK
        CASE 22 RETURN "SLOD_HUMAN" BREAK
        CASE 23 RETURN "SLOD_LARGE_QUADPED" BREAK
        CASE 24 RETURN "SLOD_SMALL_QUADPED" BREAK
        CASE 25 RETURN "S_F_M_FEMBARBER" BREAK
        CASE 26 RETURN "S_F_M_MAID_01" BREAK
        CASE 27 RETURN "S_F_M_SHOP_HIGH" BREAK
        CASE 28 RETURN "S_F_M_SWEATSHOP_01" BREAK
        CASE 29 RETURN "S_F_Y_AIRHOSTESS_01" BREAK
        CASE 30 RETURN "S_F_Y_BARTENDER_01" BREAK
        CASE 31 RETURN "S_F_Y_BAYWATCH_01" BREAK
        CASE 32 RETURN "S_F_Y_COP_01" BREAK
        CASE 33 RETURN "S_F_Y_FACTORY_01" BREAK
        CASE 34 RETURN "S_F_Y_HOOKER_01" BREAK
        CASE 35 RETURN "S_F_Y_HOOKER_02" BREAK
        CASE 36 RETURN "S_F_Y_HOOKER_03" BREAK
        CASE 37 RETURN "S_F_Y_MIGRANT_01" BREAK
        CASE 38 RETURN "S_F_Y_MOVPREM_01" BREAK
        CASE 39 RETURN "S_F_Y_RANGER_01" BREAK
        CASE 40 RETURN "S_F_Y_SCRUBS_01" BREAK
        CASE 41 RETURN "S_F_Y_SHERIFF_01" BREAK
        CASE 42 RETURN "S_F_Y_SHOP_LOW" BREAK
        CASE 43 RETURN "S_F_Y_SHOP_MID" BREAK
        CASE 44 RETURN "S_F_Y_STRIPPERLITE" BREAK
        CASE 45 RETURN "S_F_Y_STRIPPER_01" BREAK
        CASE 46 RETURN "S_F_Y_STRIPPER_02" BREAK
        CASE 47 RETURN "S_F_Y_SWEATSHOP_01" BREAK
        CASE 48 RETURN "S_M_M_AMMUCOUNTRY" BREAK
        CASE 49 RETURN "S_M_M_ARMOURED_01" BREAK
        CASE 50 RETURN "S_M_M_ARMOURED_02" BREAK
        CASE 51 RETURN "S_M_M_AUTOSHOP_01" BREAK
        CASE 52 RETURN "S_M_M_AUTOSHOP_02" BREAK
        CASE 53 RETURN "S_M_M_BOUNCER_01" BREAK
        CASE 54 RETURN "S_M_M_CHEMSEC_01" BREAK
        CASE 55 RETURN "S_M_M_CIASEC_01" BREAK
        CASE 56 RETURN "S_M_M_CNTRYBAR_01" BREAK
        CASE 57 RETURN "S_M_M_DOCKWORK_01" BREAK
        CASE 58 RETURN "S_M_M_DOCTOR_01" BREAK
        CASE 59 RETURN "S_M_M_FIBOFFICE_01" BREAK
        CASE 60 RETURN "S_M_M_FIBOFFICE_02" BREAK
        CASE 61 RETURN "S_M_M_GAFFER_01" BREAK
        CASE 62 RETURN "S_M_M_GARDENER_01" BREAK
        CASE 63 RETURN "S_M_M_GENTRANSPORT" BREAK
        CASE 64 RETURN "S_M_M_HAIRDRESS_01" BREAK
        CASE 65 RETURN "S_M_M_HIGHSEC_01" BREAK
        CASE 66 RETURN "S_M_M_HIGHSEC_02" BREAK
        CASE 67 RETURN "S_M_M_JANITOR" BREAK
        CASE 68 RETURN "S_M_M_LATHANDY_01" BREAK
        CASE 69 RETURN "S_M_M_LIFEINVAD_01" BREAK
        CASE 70 RETURN "S_M_M_LINECOOK" BREAK
        CASE 71 RETURN "S_M_M_LSMETRO_01" BREAK
        CASE 72 RETURN "S_M_M_MARIACHI_01" BREAK
        CASE 73 RETURN "S_M_M_MARINE_01" BREAK
        CASE 74 RETURN "S_M_M_MARINE_02" BREAK
        CASE 75 RETURN "S_M_M_MIGRANT_01" BREAK
        CASE 76 RETURN "S_M_M_MOVALIEN_01" BREAK
        CASE 77 RETURN "S_M_M_MOVPREM_01" BREAK
        CASE 78 RETURN "S_M_M_MOVSPACE_01" BREAK
        CASE 79 RETURN "S_M_M_PARAMEDIC_01" BREAK
        CASE 80 RETURN "S_M_M_PILOT_01" BREAK
        CASE 81 RETURN "S_M_M_PILOT_02" BREAK
        CASE 82 RETURN "S_M_M_POSTAL_01" BREAK
        CASE 83 RETURN "S_M_M_POSTAL_02" BREAK
        CASE 84 RETURN "S_M_M_PRISGUARD_01" BREAK
        CASE 85 RETURN "S_M_M_SCIENTIST_01" BREAK
        CASE 86 RETURN "S_M_M_SECURITY_01" BREAK
        CASE 87 RETURN "S_M_M_SNOWCOP_01" BREAK
        CASE 88 RETURN "S_M_M_STRPERF_01" BREAK
        CASE 89 RETURN "S_M_M_STRPREACH_01" BREAK
        CASE 90 RETURN "S_M_M_STRVEND_01" BREAK
        CASE 91 RETURN "S_M_M_TRUCKER_01" BREAK
        CASE 92 RETURN "S_M_M_UPS_01" BREAK
        CASE 93 RETURN "S_M_M_UPS_02" BREAK
        CASE 94 RETURN "S_M_O_BUSKER_01" BREAK
        CASE 95 RETURN "S_M_Y_AIRWORKER" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_6(INT choice)
    SWITCH choice
        CASE 0 RETURN S_M_Y_AMMUCITY_01 BREAK
        CASE 1 RETURN S_M_Y_ARMYMECH_01 BREAK
        CASE 2 RETURN S_M_Y_AUTOPSY_01 BREAK
        CASE 3 RETURN S_M_Y_BARMAN_01 BREAK
        CASE 4 RETURN S_M_Y_BAYWATCH_01 BREAK
        CASE 5 RETURN S_M_Y_BLACKOPS_01 BREAK
        CASE 6 RETURN S_M_Y_BLACKOPS_02 BREAK
        CASE 7 RETURN S_M_Y_BUSBOY_01 BREAK
        CASE 8 RETURN S_M_Y_CHEF_01 BREAK
        CASE 9 RETURN S_M_Y_CLOWN_01 BREAK
        CASE 10 RETURN S_M_Y_CONSTRUCT_01 BREAK
        CASE 11 RETURN S_M_Y_CONSTRUCT_02 BREAK
        CASE 12 RETURN S_M_Y_COP_01 BREAK
        CASE 13 RETURN S_M_Y_DEALER_01 BREAK
        CASE 14 RETURN S_M_Y_DEVINSEC_01 BREAK
        CASE 15 RETURN S_M_Y_DOCKWORK_01 BREAK
        CASE 16 RETURN S_M_Y_DOORMAN_01 BREAK
        CASE 17 RETURN S_M_Y_DWSERVICE_01 BREAK
        CASE 18 RETURN S_M_Y_DWSERVICE_02 BREAK
        CASE 19 RETURN S_M_Y_FACTORY_01 BREAK
        CASE 20 RETURN S_M_Y_FIREMAN_01 BREAK
        CASE 21 RETURN S_M_Y_GARBAGE BREAK
        CASE 22 RETURN S_M_Y_GRIP_01 BREAK
        CASE 23 RETURN S_M_Y_HWAYCOP_01 BREAK
        CASE 24 RETURN S_M_Y_MARINE_01 BREAK
        CASE 25 RETURN S_M_Y_MARINE_02 BREAK
        CASE 26 RETURN S_M_Y_MARINE_03 BREAK
        CASE 27 RETURN S_M_Y_MIME BREAK
        CASE 28 RETURN S_M_Y_PESTCONT_01 BREAK
        CASE 29 RETURN S_M_Y_PILOT_01 BREAK
        CASE 30 RETURN S_M_Y_PRISMUSCL_01 BREAK
        CASE 31 RETURN S_M_Y_PRISONER_01 BREAK
        CASE 32 RETURN S_M_Y_RANGER_01 BREAK
        CASE 33 RETURN S_M_Y_ROBBER_01 BREAK
        CASE 34 RETURN S_M_Y_SHERIFF_01 BREAK
        CASE 35 RETURN S_M_Y_SHOP_MASK BREAK
        CASE 36 RETURN S_M_Y_STRVEND_01 BREAK
        CASE 37 RETURN S_M_Y_SWAT_01 BREAK
        CASE 38 RETURN S_M_Y_USCG_01 BREAK
        CASE 39 RETURN S_M_Y_VALET_01 BREAK
        CASE 40 RETURN S_M_Y_WAITER_01 BREAK
        CASE 41 RETURN S_M_Y_WINCLEAN_01 BREAK
        CASE 42 RETURN S_M_Y_XMECH_01 BREAK
        CASE 43 RETURN S_M_Y_XMECH_02 BREAK
        CASE 44 RETURN U_F_M_CORPSE_01 BREAK
        CASE 45 RETURN U_F_M_DROWNED_01 BREAK
        CASE 46 RETURN U_F_M_MIRANDA BREAK
        CASE 47 RETURN U_F_M_PROMOURN_01 BREAK
        CASE 48 RETURN U_F_O_MOVIESTAR BREAK
        CASE 49 RETURN U_F_O_PROLHOST_01 BREAK
        CASE 50 RETURN U_F_Y_BIKERCHIC BREAK
        CASE 51 RETURN U_F_Y_COMJANE BREAK
        CASE 52 RETURN U_F_Y_CORPSE_01 BREAK
        CASE 53 RETURN U_F_Y_CORPSE_02 BREAK
        CASE 54 RETURN U_F_Y_HOTPOSH_01 BREAK
        CASE 55 RETURN U_F_Y_JEWELASS_01 BREAK
        CASE 56 RETURN U_F_Y_MISTRESS BREAK
        CASE 57 RETURN U_F_Y_POPPYMICH BREAK
        CASE 58 RETURN U_F_Y_PRINCESS BREAK
        CASE 59 RETURN U_F_Y_SPYACTRESS BREAK
        CASE 60 RETURN U_M_M_ALDINAPOLI BREAK
        CASE 61 RETURN U_M_M_BANKMAN BREAK
        CASE 62 RETURN U_M_M_BIKEHIRE_01 BREAK
        CASE 63 RETURN U_M_M_FIBARCHITECT BREAK
        CASE 64 RETURN U_M_M_FILMDIRECTOR BREAK
        CASE 65 RETURN U_M_M_GLENSTANK_01 BREAK
        CASE 66 RETURN U_M_M_GRIFF_01 BREAK
        CASE 67 RETURN U_M_M_JESUS_01 BREAK
        CASE 68 RETURN U_M_M_JEWELSEC_01 BREAK
        CASE 69 RETURN U_M_M_JEWELTHIEF BREAK
        CASE 70 RETURN U_M_M_MARKFOST BREAK
        CASE 71 RETURN U_M_M_PARTYTARGET BREAK
        CASE 72 RETURN U_M_M_PROLSEC_01 BREAK
        CASE 73 RETURN U_M_M_PROMOURN_01 BREAK
        CASE 74 RETURN U_M_M_RIVALPAP BREAK
        CASE 75 RETURN U_M_M_SPYACTOR BREAK
        CASE 76 RETURN U_M_M_STREETART_01 BREAK
        CASE 77 RETURN U_M_M_WILLYFIST BREAK
        CASE 78 RETURN U_M_O_FILMNOIR BREAK
        CASE 79 RETURN U_M_O_FINGURU_01 BREAK
        CASE 80 RETURN U_M_O_TAPHILLBILLY BREAK
        CASE 81 RETURN U_M_O_TRAMP_01 BREAK
        CASE 82 RETURN U_M_Y_ABNER BREAK
        CASE 83 RETURN U_M_Y_ANTONB BREAK
        CASE 84 RETURN U_M_Y_BABYD BREAK
        CASE 85 RETURN U_M_Y_BAYGOR BREAK
        CASE 86 RETURN U_M_Y_BURGERDRUG_01 BREAK
        CASE 87 RETURN U_M_Y_CHIP BREAK
        CASE 88 RETURN U_M_Y_CYCLIST_01 BREAK
        CASE 89 RETURN U_M_Y_FIBMUGGER_01 BREAK
        CASE 90 RETURN U_M_Y_GUIDO_01 BREAK
        CASE 91 RETURN U_M_Y_GUNVEND_01 BREAK
        CASE 92 RETURN U_M_Y_HIPPIE_01 BREAK
        CASE 93 RETURN U_M_Y_IMPORAGE BREAK
        CASE 94 RETURN U_M_Y_JUSTIN BREAK
        CASE 95 RETURN U_M_Y_MANI BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_6(INT choice)
    SWITCH choice
        CASE 0 RETURN "S_M_Y_AMMUCITY_01" BREAK
        CASE 1 RETURN "S_M_Y_ARMYMECH_01" BREAK
        CASE 2 RETURN "S_M_Y_AUTOPSY_01" BREAK
        CASE 3 RETURN "S_M_Y_BARMAN_01" BREAK
        CASE 4 RETURN "S_M_Y_BAYWATCH_01" BREAK
        CASE 5 RETURN "S_M_Y_BLACKOPS_01" BREAK
        CASE 6 RETURN "S_M_Y_BLACKOPS_02" BREAK
        CASE 7 RETURN "S_M_Y_BUSBOY_01" BREAK
        CASE 8 RETURN "S_M_Y_CHEF_01" BREAK
        CASE 9 RETURN "S_M_Y_CLOWN_01" BREAK
        CASE 10 RETURN "S_M_Y_CONSTRUCT_01" BREAK
        CASE 11 RETURN "S_M_Y_CONSTRUCT_02" BREAK
        CASE 12 RETURN "S_M_Y_COP_01" BREAK
        CASE 13 RETURN "S_M_Y_DEALER_01" BREAK
        CASE 14 RETURN "S_M_Y_DEVINSEC_01" BREAK
        CASE 15 RETURN "S_M_Y_DOCKWORK_01" BREAK
        CASE 16 RETURN "S_M_Y_DOORMAN_01" BREAK
        CASE 17 RETURN "S_M_Y_DWSERVICE_01" BREAK
        CASE 18 RETURN "S_M_Y_DWSERVICE_02" BREAK
        CASE 19 RETURN "S_M_Y_FACTORY_01" BREAK
        CASE 20 RETURN "S_M_Y_FIREMAN_01" BREAK
        CASE 21 RETURN "S_M_Y_GARBAGE" BREAK
        CASE 22 RETURN "S_M_Y_GRIP_01" BREAK
        CASE 23 RETURN "S_M_Y_HWAYCOP_01" BREAK
        CASE 24 RETURN "S_M_Y_MARINE_01" BREAK
        CASE 25 RETURN "S_M_Y_MARINE_02" BREAK
        CASE 26 RETURN "S_M_Y_MARINE_03" BREAK
        CASE 27 RETURN "S_M_Y_MIME" BREAK
        CASE 28 RETURN "S_M_Y_PESTCONT_01" BREAK
        CASE 29 RETURN "S_M_Y_PILOT_01" BREAK
        CASE 30 RETURN "S_M_Y_PRISMUSCL_01" BREAK
        CASE 31 RETURN "S_M_Y_PRISONER_01" BREAK
        CASE 32 RETURN "S_M_Y_RANGER_01" BREAK
        CASE 33 RETURN "S_M_Y_ROBBER_01" BREAK
        CASE 34 RETURN "S_M_Y_SHERIFF_01" BREAK
        CASE 35 RETURN "S_M_Y_SHOP_MASK" BREAK
        CASE 36 RETURN "S_M_Y_STRVEND_01" BREAK
        CASE 37 RETURN "S_M_Y_SWAT_01" BREAK
        CASE 38 RETURN "S_M_Y_USCG_01" BREAK
        CASE 39 RETURN "S_M_Y_VALET_01" BREAK
        CASE 40 RETURN "S_M_Y_WAITER_01" BREAK
        CASE 41 RETURN "S_M_Y_WINCLEAN_01" BREAK
        CASE 42 RETURN "S_M_Y_XMECH_01" BREAK
        CASE 43 RETURN "S_M_Y_XMECH_02" BREAK
        CASE 44 RETURN "U_F_M_CORPSE_01" BREAK
        CASE 45 RETURN "U_F_M_DROWNED_01" BREAK
        CASE 46 RETURN "U_F_M_MIRANDA" BREAK
        CASE 47 RETURN "U_F_M_PROMOURN_01" BREAK
        CASE 48 RETURN "U_F_O_MOVIESTAR" BREAK
        CASE 49 RETURN "U_F_O_PROLHOST_01" BREAK
        CASE 50 RETURN "U_F_Y_BIKERCHIC" BREAK
        CASE 51 RETURN "U_F_Y_COMJANE" BREAK
        CASE 52 RETURN "U_F_Y_CORPSE_01" BREAK
        CASE 53 RETURN "U_F_Y_CORPSE_02" BREAK
        CASE 54 RETURN "U_F_Y_HOTPOSH_01" BREAK
        CASE 55 RETURN "U_F_Y_JEWELASS_01" BREAK
        CASE 56 RETURN "U_F_Y_MISTRESS" BREAK
        CASE 57 RETURN "U_F_Y_POPPYMICH" BREAK
        CASE 58 RETURN "U_F_Y_PRINCESS" BREAK
        CASE 59 RETURN "U_F_Y_SPYACTRESS" BREAK
        CASE 60 RETURN "U_M_M_ALDINAPOLI" BREAK
        CASE 61 RETURN "U_M_M_BANKMAN" BREAK
        CASE 62 RETURN "U_M_M_BIKEHIRE_01" BREAK
        CASE 63 RETURN "U_M_M_FIBARCHITECT" BREAK
        CASE 64 RETURN "U_M_M_FILMDIRECTOR" BREAK
        CASE 65 RETURN "U_M_M_GLENSTANK_01" BREAK
        CASE 66 RETURN "U_M_M_GRIFF_01" BREAK
        CASE 67 RETURN "U_M_M_JESUS_01" BREAK
        CASE 68 RETURN "U_M_M_JEWELSEC_01" BREAK
        CASE 69 RETURN "U_M_M_JEWELTHIEF" BREAK
        CASE 70 RETURN "U_M_M_MARKFOST" BREAK
        CASE 71 RETURN "U_M_M_PARTYTARGET" BREAK
        CASE 72 RETURN "U_M_M_PROLSEC_01" BREAK
        CASE 73 RETURN "U_M_M_PROMOURN_01" BREAK
        CASE 74 RETURN "U_M_M_RIVALPAP" BREAK
        CASE 75 RETURN "U_M_M_SPYACTOR" BREAK
        CASE 76 RETURN "U_M_M_STREETART_01" BREAK
        CASE 77 RETURN "U_M_M_WILLYFIST" BREAK
        CASE 78 RETURN "U_M_O_FILMNOIR" BREAK
        CASE 79 RETURN "U_M_O_FINGURU_01" BREAK
        CASE 80 RETURN "U_M_O_TAPHILLBILLY" BREAK
        CASE 81 RETURN "U_M_O_TRAMP_01" BREAK
        CASE 82 RETURN "U_M_Y_ABNER" BREAK
        CASE 83 RETURN "U_M_Y_ANTONB" BREAK
        CASE 84 RETURN "U_M_Y_BABYD" BREAK
        CASE 85 RETURN "U_M_Y_BAYGOR" BREAK
        CASE 86 RETURN "U_M_Y_BURGERDRUG_01" BREAK
        CASE 87 RETURN "U_M_Y_CHIP" BREAK
        CASE 88 RETURN "U_M_Y_CYCLIST_01" BREAK
        CASE 89 RETURN "U_M_Y_FIBMUGGER_01" BREAK
        CASE 90 RETURN "U_M_Y_GUIDO_01" BREAK
        CASE 91 RETURN "U_M_Y_GUNVEND_01" BREAK
        CASE 92 RETURN "U_M_Y_HIPPIE_01" BREAK
        CASE 93 RETURN "U_M_Y_IMPORAGE" BREAK
        CASE 94 RETURN "U_M_Y_JUSTIN" BREAK
        CASE 95 RETURN "U_M_Y_MANI" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_PAGE_7(INT choice)
    SWITCH choice
        CASE 0 RETURN U_M_Y_MILITARYBUM BREAK
        CASE 1 RETURN U_M_Y_PAPARAZZI BREAK
        CASE 2 RETURN U_M_Y_PARTY_01 BREAK
        CASE 3 RETURN U_M_Y_POGO_01 BREAK
        CASE 4 RETURN U_M_Y_PRISONER_01 BREAK
        CASE 5 RETURN U_M_Y_PROLDRIVER_01 BREAK
        CASE 6 RETURN U_M_Y_RSRANGER_01 BREAK
        CASE 7 RETURN U_M_Y_SBIKE BREAK
        CASE 8 RETURN U_M_Y_STAGGRM_01 BREAK
        CASE 9 RETURN U_M_Y_TATTOO_01 BREAK
        CASE 10 RETURN U_M_Y_ZOMBIE_01 BREAK
    ENDSWITCH
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_PAGE_7(INT choice)
    SWITCH choice
        CASE 0 RETURN "U_M_Y_MILITARYBUM" BREAK
        CASE 1 RETURN "U_M_Y_PAPARAZZI" BREAK
        CASE 2 RETURN "U_M_Y_PARTY_01" BREAK
        CASE 3 RETURN "U_M_Y_POGO_01" BREAK
        CASE 4 RETURN "U_M_Y_PRISONER_01" BREAK
        CASE 5 RETURN "U_M_Y_PROLDRIVER_01" BREAK
        CASE 6 RETURN "U_M_Y_RSRANGER_01" BREAK
        CASE 7 RETURN "U_M_Y_SBIKE" BREAK
        CASE 8 RETURN "U_M_Y_STAGGRM_01" BREAK
        CASE 9 RETURN "U_M_Y_TATTOO_01" BREAK
        CASE 10 RETURN "U_M_Y_ZOMBIE_01" BREAK
    ENDSWITCH
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC MODEL_NAMES PED_MODEL_FOR_CHOICE(INT choice)
    IF choice < 0 OR choice >= PED_CHOICE_COUNT() RETURN PLAYER_ZERO ENDIF
    IF choice < 96 RETURN PED_MODEL_PAGE_0(choice - 0) ENDIF
    IF choice < 192 RETURN PED_MODEL_PAGE_1(choice - 96) ENDIF
    IF choice < 288 RETURN PED_MODEL_PAGE_2(choice - 192) ENDIF
    IF choice < 384 RETURN PED_MODEL_PAGE_3(choice - 288) ENDIF
    IF choice < 480 RETURN PED_MODEL_PAGE_4(choice - 384) ENDIF
    IF choice < 576 RETURN PED_MODEL_PAGE_5(choice - 480) ENDIF
    IF choice < 672 RETURN PED_MODEL_PAGE_6(choice - 576) ENDIF
    IF choice < 768 RETURN PED_MODEL_PAGE_7(choice - 672) ENDIF
    RETURN PLAYER_ZERO
ENDFUNC

FUNC STRING PED_NAME_FOR_CHOICE(INT choice)
    IF choice < 0 OR choice >= PED_CHOICE_COUNT() RETURN "UNKNOWN_PED" ENDIF
    IF choice < 96 RETURN PED_NAME_PAGE_0(choice - 0) ENDIF
    IF choice < 192 RETURN PED_NAME_PAGE_1(choice - 96) ENDIF
    IF choice < 288 RETURN PED_NAME_PAGE_2(choice - 192) ENDIF
    IF choice < 384 RETURN PED_NAME_PAGE_3(choice - 288) ENDIF
    IF choice < 480 RETURN PED_NAME_PAGE_4(choice - 384) ENDIF
    IF choice < 576 RETURN PED_NAME_PAGE_5(choice - 480) ENDIF
    IF choice < 672 RETURN PED_NAME_PAGE_6(choice - 576) ENDIF
    IF choice < 768 RETURN PED_NAME_PAGE_7(choice - 672) ENDIF
    RETURN "UNKNOWN_PED"
ENDFUNC

FUNC INT FIND_PED_CHOICE_BY_NAME(STRING modelName)
    INT wantedHash = GET_HASH_KEY(modelName)
    INT choice = 0
    WHILE choice < PED_CHOICE_COUNT()
        IF GET_HASH_KEY(PED_NAME_FOR_CHOICE(choice)) = wantedHash RETURN choice ENDIF
        choice = choice + 1
    ENDWHILE
    RETURN -1
ENDFUNC

FUNC INT SLOT_FOR_MODEL(MODEL_NAMES model)
    IF model = PLAYER_ONE RETURN 1 ENDIF
    IF model = PLAYER_TWO RETURN 2 ENDIF
    RETURN 0
ENDFUNC

PROC SAVE_ACTIVE_CHARACTER_PED()

    MODEL_NAMES currentModel = GET_ENTITY_MODEL(PLAYER_PED_ID())
    INT liveSlot = SLOT_FOR_MODEL(currentModel)
    IF liveSlot = 0 g_franklin_ped = currentModel ENDIF
    IF liveSlot = 1 g_michael_ped = currentModel ENDIF
    IF liveSlot = 2 g_trevor_ped = currentModel ENDIF
ENDPROC

FUNC MODEL_NAMES SAVED_CHARACTER_PED(INT slot)
    IF slot = 0 RETURN g_franklin_ped ENDIF
    IF slot = 1 RETURN g_michael_ped ENDIF
    RETURN g_trevor_ped
ENDFUNC

FUNC INT PED_CHOICE_FOR_MODEL(MODEL_NAMES model)
    INT choice = 0
    WHILE choice < PED_CHOICE_COUNT()
        IF PED_MODEL_FOR_CHOICE(choice) = model RETURN choice ENDIF
        choice = choice + 1
    ENDWHILE
    RETURN -1
ENDFUNC

FUNC STRING CURRENT_PED_SEARCH_LABEL()
    RETURN g_current_ped_label
ENDFUNC

PROC REFRESH_CURRENT_PED_LABEL()
    MODEL_NAMES currentModel = GET_ENTITY_MODEL(PLAYER_PED_ID())
    INT catalogChoice = 0
    IF currentModel = g_current_ped_label_model EXIT ENDIF
    catalogChoice = PED_CHOICE_FOR_MODEL(currentModel)
    IF catalogChoice >= 0
        g_current_ped_label_model = currentModel
        g_current_ped_label = PED_NAME_FOR_CHOICE(catalogChoice)
    ENDIF
ENDPROC

FUNC STRING CURRENT_VEHICLE_SEARCH_LABEL()
    IF IS_PED_IN_ANY_VEHICLE(PLAYER_PED_ID())
        RETURN GET_DISPLAY_NAME_FROM_VEHICLE_MODEL(GET_ENTITY_MODEL(GET_VEHICLE_PED_IS_IN(PLAYER_PED_ID())))
    ENDIF
    RETURN "TYPE MODEL"
ENDFUNC

PROC REQUEST_PED_CHANGE(MODEL_NAMES model)
    IF g_ped_change_pending OR IS_PED_IN_ANY_VEHICLE(PLAYER_PED_ID()) EXIT ENDIF
    IF NOT IS_MODEL_IN_CDIMAGE(model) OR NOT IS_MODEL_VALID(model) EXIT ENDIF
    REQUEST_MODEL(model)
    g_pending_ped_model = model
    g_ped_change_pending = TRUE
    g_ped_request_time = GET_GAME_TIMER()
ENDPROC

PROC FINISH_PED_CHANGE()
    IF HAS_MODEL_LOADED(g_pending_ped_model)
        SET_PLAYER_MODEL(PLAYER_ID(), g_pending_ped_model)
        SET_PED_DEFAULT_COMPONENT_VARIATION(PLAYER_PED_ID())
        SAVE_ACTIVE_CHARACTER_PED()
    ENDIF
    SET_MODEL_AS_NO_LONGER_NEEDED(g_pending_ped_model)
    g_ped_change_pending = FALSE
ENDPROC

FUNC MODEL_NAMES STORY_MODEL_FOR_SLOT(INT slot)
    IF slot = 1 RETURN PLAYER_ONE ENDIF
    IF slot = 2 RETURN PLAYER_TWO ENDIF
    RETURN PLAYER_ZERO
ENDFUNC

PROC PROCESS_PED_DEATH_RECOVERY()
    MODEL_NAMES currentModel = GET_ENTITY_MODEL(PLAYER_PED_ID())
    MODEL_NAMES storyModel = STORY_MODEL_FOR_SLOT(g_character_slot)
    BOOL tripped = FALSE
    IF IS_PED_INJURED(PLAYER_PED_ID()) tripped = TRUE ENDIF
    IF IS_ENTITY_DEAD(PLAYER_PED_ID()) tripped = TRUE ENDIF
    IF tripped
        IF currentModel != storyModel AND NOT g_ped_change_pending
            IF NOT g_ped_death_recovery
                g_ped_pre_death_model = currentModel
                g_ped_death_recovery = TRUE
            ENDIF
            IF IS_MODEL_IN_CDIMAGE(storyModel) AND IS_MODEL_VALID(storyModel)
                SET_PLAYER_MODEL(PLAYER_ID(), storyModel)
                SET_PED_DEFAULT_COMPONENT_VARIATION(PLAYER_PED_ID())
            ENDIF
        ENDIF
        g_ped_stable_control_ticks = 0
    ELIF g_ped_death_recovery
        IF NOT g_ped_change_pending AND IS_PLAYER_CONTROL_ON(PLAYER_ID()) AND NOT IS_PED_IN_ANY_VEHICLE(PLAYER_PED_ID())
            g_ped_stable_control_ticks = g_ped_stable_control_ticks + 1
            IF g_ped_stable_control_ticks >= 90
                g_ped_death_recovery = FALSE
                g_ped_stable_control_ticks = 0
                SAVE_ACTIVE_CHARACTER_PED()
                REQUEST_PED_CHANGE(g_ped_pre_death_model)
            ENDIF
        ELSE
            g_ped_stable_control_ticks = 0
        ENDIF
    ENDIF
ENDPROC

PROC APPLY_CHARACTER_PROFILE(INT slot)
    g_character_slot = slot
    REQUEST_PED_CHANGE(SAVED_CHARACTER_PED(slot))
ENDPROC

PROC ADJUST_PED_SELECTOR(INT direction)
    INT nextSlot = 0
    IF g_item = 2
        nextSlot = g_character_slot + direction
        IF nextSlot < 0 nextSlot = 2 ENDIF
        IF nextSlot > 2 nextSlot = 0 ENDIF
        SAVE_ACTIVE_CHARACTER_PED()
        APPLY_CHARACTER_PROFILE(nextSlot)
    ENDIF
ENDPROC

PROC DRAW_CHARACTER_PROFILE(FLOAT y, BOOL selected)
    IF g_character_slot = 0 DRAW_OPTION(y, "Character Profile:", "< Michael >", selected, 3) ENDIF
    IF g_character_slot = 1 DRAW_OPTION(y, "Character Profile:", "< Franklin >", selected, 3) ENDIF
    IF g_character_slot = 2 DRAW_OPTION(y, "Character Profile:", "< Trevor >", selected, 3) ENDIF
ENDPROC

PROC DRAW_PED_PAGE()
    MENU_TEXT(g_menu_x - 0.130, 0.198, 0.270, 255, 255, 255, "PED CHANGER")
    DRAW_MENU_VERSION_TAG()
    INT index = g_scroll
    INT row = 0
    WHILE row < 8 AND index < PED_CHOICE_COUNT() + 3
        FLOAT y = 0.268 + (TO_FLOAT(row) * ROW_H)
        IF index = 0
            IF g_ped_search_not_found
                DRAW_OPTION(y, "PED Search", "NOT FOUND", g_item = index, 0)
            ELIF g_ped_search_has_value
                DRAW_OPTION(y, "PED Search", g_ped_search_value, g_item = index, 1)
            ELSE
                DRAW_OPTION(y, "PED Search", CURRENT_PED_SEARCH_LABEL(), g_item = index, 2)
            ENDIF
        ELIF index = 1
            DRAW_OPTION(y, "Random PED", "APPLY", g_item = index, 2)
        ELIF index = 2
            DRAW_CHARACTER_PROFILE(y, g_item = index)
        ELSE
            DRAW_OPTION(y, "PED:", PED_NAME_FOR_CHOICE(index - 3), g_item = index, 2)
        ENDIF
        index = index + 1
        row = row + 1
    ENDWHILE
ENDPROC

FUNC INT STAT_ACTIVE_SLOT()
    RETURN SLOT_FOR_MODEL(GET_ENTITY_MODEL(PLAYER_PED_ID()))
ENDFUNC

PROC STAT_ENUM_FOR_SLOT(INT base, INT slot, STATSENUM &statOut)
    IF slot = 1
        IF base = 0 statOut = SP1_STAMINA ENDIF
        IF base = 1 statOut = SP1_STRENGTH ENDIF
        IF base = 2 statOut = SP1_LUNG_CAPACITY ENDIF
        IF base = 3 statOut = SP1_FLYING_ABILITY ENDIF
        IF base = 4 statOut = SP1_SHOOTING_ABILITY ENDIF
        IF base = 5 statOut = SP1_STEALTH_ABILITY ENDIF
        IF base = 6 statOut = SP1_WHEELIE_ABILITY ENDIF
        IF base = 7 statOut = SP1_SPECIAL_ABILITY_UNLOCKED ENDIF
    ELIF slot = 2
        IF base = 0 statOut = SP2_STAMINA ENDIF
        IF base = 1 statOut = SP2_STRENGTH ENDIF
        IF base = 2 statOut = SP2_LUNG_CAPACITY ENDIF
        IF base = 3 statOut = SP2_FLYING_ABILITY ENDIF
        IF base = 4 statOut = SP2_SHOOTING_ABILITY ENDIF
        IF base = 5 statOut = SP2_STEALTH_ABILITY ENDIF
        IF base = 6 statOut = SP2_WHEELIE_ABILITY ENDIF
        IF base = 7 statOut = SP2_SPECIAL_ABILITY_UNLOCKED ENDIF
    ELSE
        IF base = 0 statOut = SP0_STAMINA ENDIF
        IF base = 1 statOut = SP0_STRENGTH ENDIF
        IF base = 2 statOut = SP0_LUNG_CAPACITY ENDIF
        IF base = 3 statOut = SP0_FLYING_ABILITY ENDIF
        IF base = 4 statOut = SP0_SHOOTING_ABILITY ENDIF
        IF base = 5 statOut = SP0_STEALTH_ABILITY ENDIF
        IF base = 6 statOut = SP0_WHEELIE_ABILITY ENDIF
        IF base = 7 statOut = SP0_SPECIAL_ABILITY_UNLOCKED ENDIF
    ENDIF
ENDPROC

PROC APPLY_RANDOM_PED()
    INT attempts = 0
    INT choice = 0
    WHILE attempts < 8
        choice = GET_RANDOM_INT_IN_RANGE(0, PED_CHOICE_COUNT())
        IF NOT g_ped_change_pending AND NOT IS_PED_IN_ANY_VEHICLE(PLAYER_PED_ID())
            IF IS_MODEL_IN_CDIMAGE(PED_MODEL_FOR_CHOICE(choice)) AND IS_MODEL_VALID(PED_MODEL_FOR_CHOICE(choice))
                SAVE_ACTIVE_CHARACTER_PED()
                g_ped_choice = choice
                g_ped_search_not_found = FALSE
                g_ped_search_has_value = TRUE
                g_ped_search_is_custom = FALSE
                g_ped_search_value = PED_NAME_FOR_CHOICE(choice)
                REQUEST_PED_CHANGE(PED_MODEL_FOR_CHOICE(choice))
                EXIT
            ENDIF
        ELSE
            EXIT
        ENDIF
        attempts = attempts + 1
    ENDWHILE
ENDPROC

PROC STAT_READ_SLOT(INT slot, INT base, INT &valueOut)
    STATSENUM stat = SP0_STAMINA
    FLOAT stored = 0.0
    STAT_ENUM_FOR_SLOT(base, slot, stat)
    IF STAT_GET_FLOAT(stat, stored)
        valueOut = ROUND(stored)
    ENDIF
ENDPROC

PROC STAT_WRITE_SLOT(INT slot, INT base, INT value)
    STATSENUM stat = SP0_STAMINA
    STAT_ENUM_FOR_SLOT(base, slot, stat)
    STAT_SET_FLOAT(stat, TO_FLOAT(value))
    STAT_SET_INT(stat, value)
ENDPROC

PROC LOAD_STAT_MANAGER()
    INT slot = STAT_ACTIVE_SLOT()
    g_character_slot = slot
    STAT_READ_SLOT(slot, 0, g_stat_stamina)
    STAT_READ_SLOT(slot, 1, g_stat_strength)
    STAT_READ_SLOT(slot, 2, g_stat_lung)
    STAT_READ_SLOT(slot, 3, g_stat_flying)
    STAT_READ_SLOT(slot, 4, g_stat_shooting)
    STAT_READ_SLOT(slot, 5, g_stat_stealth)
    STAT_READ_SLOT(slot, 6, g_stat_driving)
    STAT_READ_SLOT(slot, 7, g_stat_wheelie)
ENDPROC

PROC ADJUST_STAT_VALUE(INT base, INT direction)
    INT slot = STAT_ACTIVE_SLOT()
    IF slot != g_character_slot
        LOAD_STAT_MANAGER()
        slot = g_character_slot
    ENDIF
    INT value = 0
    IF base = 0 value = g_stat_stamina ENDIF
    IF base = 1 value = g_stat_strength ENDIF
    IF base = 2 value = g_stat_lung ENDIF
    IF base = 3 value = g_stat_flying ENDIF
    IF base = 4 value = g_stat_shooting ENDIF
    IF base = 5 value = g_stat_stealth ENDIF
    IF base = 6 value = g_stat_driving ENDIF
    IF base = 7 value = g_stat_wheelie ENDIF
    value = value + (direction * 5)
    IF value < 0 value = 0 ENDIF
    IF value > 100 value = 100 ENDIF
    STAT_WRITE_SLOT(slot, base, value)
    IF base = 0 g_stat_stamina = value ENDIF
    IF base = 1 g_stat_strength = value ENDIF
    IF base = 2 g_stat_lung = value ENDIF
    IF base = 3 g_stat_flying = value ENDIF
    IF base = 4 g_stat_shooting = value ENDIF
    IF base = 5 g_stat_stealth = value ENDIF
    IF base = 6 g_stat_driving = value ENDIF
    IF base = 7 g_stat_wheelie = value ENDIF
ENDPROC

PROC MAX_ALL_STATS()
    INT slot = STAT_ACTIVE_SLOT()
    g_character_slot = slot
    STAT_WRITE_SLOT(slot, 0, 100)
    STAT_WRITE_SLOT(slot, 1, 100)
    STAT_WRITE_SLOT(slot, 2, 100)
    STAT_WRITE_SLOT(slot, 3, 100)
    STAT_WRITE_SLOT(slot, 4, 100)
    STAT_WRITE_SLOT(slot, 5, 100)
    STAT_WRITE_SLOT(slot, 6, 100)
    STAT_WRITE_SLOT(slot, 7, 100)
    LOAD_STAT_MANAGER()
ENDPROC
